# Part 3: Cas Pràctic Complet - Sistema de Cotitzacions per Email
## JCM Technologies - Departament de R+D

<table style="margin: 0; text-align: left; width:100%; border: 2px solid #2e86ab;">
    <tr>
        <td style="width: 150px; vertical-align: middle; padding: 20px;">
            <img src="https://raw.githubusercontent.com/googlefonts/noto-emoji/main/png/128/emoji_u1f4e7.png" width="120" style="display: block;" />
        </td>
        <td style="padding: 20px;">
            <h2 style="color:#2e86ab; margin: 0;">Sistema Multi-Agent per Cotitzacions</h2>
            <p style="color:#333; margin-top: 10px;"><strong>Cas d'ús real:</strong> Automatitzar el procés de sol·licitud i anàlisi de cotitzacions de components electrònics via email.</p>
            <ul style="color:#333; margin-top: 10px;">
                <li>5 agents especialitzats col·laborant</li>
                <li>Parsing intel·ligent d'emails no estructurats</li>
                <li>Comparativa multi-proveïdor automatitzada</li>
                <li>Generació d'informes executius</li>
            </ul>
            <p style="color:#ff7800; margin: 10px 0 0 0;"><strong>Durada estimada:</strong> 110 minuts (~2 hores)</p>
        </td>
    </tr>
</table>

---
## 📚 Continguts

1. **Visió general del sistema** (10 min)
2. **Preparació de dades i templates** (10 min)
3. **Agent 1: BOM Analyzer** (10 min)
4. **Agent 2: RFQ Generator** (15 min)
5. **Enviar emails REALS amb Gmail API** (20 min)
6. **Dinàmica de la formació: Companys responen** (15 min)
7. **Agent 3: Email Parser** (20 min) ⭐
8. **Agents 4 i 5: Comparació i Informe** (25 min)
9. **Integració completa del sistema** (10 min)
10. **Bonus: Millores i properes passes** (10 min)

---
## 1. Visió General del Sistema

Construirem un sistema real que automatitza el procés de cotització de components electrònics.

### 1.1 El problema real

**Situació actual a moltes empreses (potser també a JCM):**

1. 📋 Tens un BOM amb 50 components
2. ✉️ Envies emails a 3-5 proveïdors demanant preus
3. 📥 Reps respostes en formats diversos:
   - Taules ben estructurades
   - Text lliure
   - PDFs
   - Formats caòtics
4. 📊 Has de comparar manualment:
   - Preus
   - Stock disponible
   - Lead times
   - Condicions de pagament
5. 📝 Generar informe per la direcció

**Temps invertit:** 2-4 hores per BOM

**Errors comuns:**
- Perdre informació en la transcripció manual
- No comparar tots els proveïdors
- No detectar condicions ocultes (MOQ, lead times llargs)
- Informes inconsistents

### 1.2 La solució: Sistema Multi-Agent

**Workflow automatitzat:**

```
INPUT: BOM Excel
  ↓
┌─────────────────────────────────────────────────┐
│ Agent 1: BOM ANALYZER                          │
│ - Llegeix Excel                                │
│ - Identifica components crítics/cars           │
│ - Prioritza per cost/criticitat                │
└─────────────────────────────────────────────────┘
  ↓ Llista components a cotitzar
┌─────────────────────────────────────────────────┐
│ Agent 2: RFQ GENERATOR                         │
│ - Genera emails professionals                  │
│ - Personalitza per proveïdor                   │
│ - Inclou detalls tècnics                       │
└─────────────────────────────────────────────────┘
  ↓ Emails RFQ generats
┌─────────────────────────────────────────────────┐
│ [ENVIAR VIA GMAIL API] → Companys de JCM      │
│ - Cada company rep un RFQ real                 │
│ - Responen simulant proveïdors:                │
│   * Grup 1: Format taula estructurada          │
│   * Grup 2: Text lliure conversacional         │
│   * Grup 3: Format caòtic/realista             │
└─────────────────────────────────────────────────┘
  ↓ Emails REALS amb cotitzacions
┌─────────────────────────────────────────────────┐
│ Agent 3: EMAIL PARSER ⭐ (clau!)               │
│ - Extreu preus de formats diversos             │
│ - Normalitza dades                             │
│ - Gestiona informació incompleta               │
│ - Detecta condicions especials                 │
└─────────────────────────────────────────────────┘
  ↓ Dades estructurades (Pydantic)
┌─────────────────────────────────────────────────┐
│ Agent 4: PRICE COMPARATOR                      │
│ - Compara preus multi-proveïdor                │
│ - Identifica millors ofertes                   │
│ - Detecta alertes (stock, lead time)           │
│ - Calcula costos totals                        │
└─────────────────────────────────────────────────┘
  ↓ Anàlisi comparativa
┌─────────────────────────────────────────────────┐
│ Agent 5: REPORT GENERATOR                      │
│ - Informe executiu                             │
│ - Taules comparatives                          │
│ - Recomanacions de compra                      │
│ - Export Markdown/JSON/Excel                   │
└─────────────────────────────────────────────────┘
  ↓
OUTPUT: Informe complet de cotització
```

**Temps invertit amb agents:** 5-10 minuts  
**Reducció:** 90-95% del temps  
**Qualitat:** Consistent, sense errors humans

### 1.3 Per què aquest cas d'ús és excel·lent?

**1. Reflecteix la realitat**
- Moltes empreses NO tenen APIs de proveïdors
- El correu electrònic és el canal principal
- Formats diversos i no estructurats

**2. Demostra el poder dels LLMs**
- Parsing de text no estructurat
- Comprensió de context
- Extracció d'informació clau
- Normalització de dades

**3. Aplicable a altres casos**
- Facturas i albarans
- Respostes a RFQs
- Comunicació amb clients
- Processament de documentació tècnica

**4. ROI immediat**
- Estalvi de temps mesurable
- Reducció d'errors
- Millor presa de decisions
- Escalable a múltiples BOMs

### 1.4 Tecnologies que usarem

**Frameworks i llibreries:**
- ✅ CrewAI (orquestració d'agents)
- ✅ Google Gemini (LLM)
- ✅ Pydantic (structured outputs)
- ✅ Pandas (manipulació de dades)
- ✅ Python standard library
- ✅ Gmail API (enviar i rebre emails reals)

**Dinàmica de la formació:**
- Els companys actuen com a proveïdors
- Responen amb 3 formats diferents (realistes)
- Emails 100% reals via Gmail

---
## 2. Preparació de Dades i Templates

Abans de crear els agents, preparem les dades necessàries.

### 2.0 LLM a utilitzar

En aquest cas farem servir els models d'OpenAI, en concret el gpt-4o-mini. 

He provat de fer-ho córrer amb els models gratuïts de Google i no me n'he sortit.

In [1]:
import os
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process

load_dotenv()

# ═══════════════════════════════════════════════════════════
# CONFIGURACIÓ OPENAI
# ═══════════════════════════════════════════════════════════

# Model OpenAI (CrewAI detecta automàticament OpenAI pel prefix)
OPENAI_MODEL = "gpt-4o-mini"  # Ràpid i econòmic
# OPENAI_MODEL = "gpt-4o"     # Més intel·ligent però més car
# OPENAI_MODEL = "gpt-4-turbo" # Alternat iva

# Verificar API Key
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise ValueError("❌ OPENAI_API_KEY no trobada al .env!")

print("🤖 Configuració LLM:")
print(f"   Provider: OpenAI")
print(f"   Model: {OPENAI_MODEL}")
print(f"   API Key: ...{OPENAI_API_KEY[-8:]}")
print()

🤖 Configuració LLM:
   Provider: OpenAI
   Model: gpt-4o-mini
   API Key: ...ROpI4sAA



### 2.1 BOM Excel REAL de JCM

Usarem un BOM **real** de JCM Technologies (TESTBOM) per fer la formació més pràctica i rellevant:

In [2]:
import pandas as pd
import os
import shutil

# Crear directori si no existeix
os.makedirs('data', exist_ok=True)

# IMPORTANT: Aquest BOM és REAL de JCM Technologies
# Cal tenir el fitxer Bill_of_Materials-TESTBOM.xlsx a la carpeta del projecte

print("📋 Copiant BOM real de JCM...\n")

# Si el fitxer no està a data/, copiar-lo
source_file = 'Bill_of_Materials-TESTBOM.xlsx'
dest_file = 'data/Bill_of_Materials-TESTBOM.xlsx'

if os.path.exists(source_file) and not os.path.exists(dest_file):
    shutil.copy(source_file, dest_file)
    print(f"✅ BOM copiat a {dest_file}")
elif os.path.exists(dest_file):
    print(f"✅ BOM ja existeix a {dest_file}")
else:
    print(f"⚠️ ATENCIÓ: No s'ha trobat {source_file}")
    print(f"   Cal col·locar el fitxer a la carpeta del projecte.")

# Llegir i mostrar informació del BOM
try:
    # El BOM real té metadata a les primeres 6 files, headers a la fila 7
    df_bom = pd.read_excel(dest_file, skiprows=7)
    
    # Filtrar només files amb MATERIAL (components reals)
    df_bom = df_bom[df_bom['MATERIAL'].notna()].copy()
    # Netejar MATERIAL: eliminar espais i convertir floats a ints
    df_bom['MATERIAL'] = df_bom['MATERIAL'].astype(str).str.strip()
    # Si hi ha ".0" al final (de floats), eliminar-lo
    df_bom['MATERIAL'] = df_bom['MATERIAL'].str.replace(r'\.0+$', '', regex=True)
    # Filtrar només números
    df_bom = df_bom[df_bom['MATERIAL'].str.match(r'^\d+$', na=False)].copy()
    
    print(f"\n📊 BOM Real de JCM Technologies - TESTBOM")
    print(f"   Variant: S-TESTBOM")
    print(f"   Total components: {len(df_bom)}")
    print(f"   Total quantitat: {df_bom['Quantity'].sum():.0f} unitats\n")
    
    print("📋 Primers 10 components:")
    display(df_bom[['MATERIAL', 'Description', 'Quantity']].head(10))
    
except FileNotFoundError:
    print("\n❌ No s'ha pogut llegir el BOM.")
    print("   Assegura't que el fitxer Bill_of_Materials-TESTBOM.xlsx")
    print("   està a la carpeta del projecte o a data/")
except Exception as e:
    print(f"\n❌ Error llegint el BOM: {e}")

📋 Copiant BOM real de JCM...

✅ BOM ja existeix a data/Bill_of_Materials-TESTBOM.xlsx

📊 BOM Real de JCM Technologies - TESTBOM
   Variant: S-TESTBOM
   Total components: 23
   Total quantitat: 37 unitats

📋 Primers 10 components:


MATERIAL                               Description  Quantity
0  3003737  DIODE BRID.RECTI AM156 40V 1A D8,5*5,1MM       1.0
1  3003522    BUZZER MAG 2KHZ 1.5VDC 12MM EXTERNALTH       1.0
2  3000598     CAP CERAMIC 100N SMD 0603 16V 10% Y5V       4.0
3  3000719            CAP ALUM 10U TH 5x11MM 25V 20%       1.0
4  3003780  DIODE SCHOTTKY D BAT54A 30V 200MA SOT-23       1.0
5  3003681     DIODE ZENER BZT55C 5V6 500MW SOD80 2P       1.0
6  3003775         DIODE LED GREEN 570NM 0805 SMD SP       1.0
7  3003762              DIODE LED RED 650NM 0805 SMD       1.0
8  3003669                  DIODE 1N 4148 SMD SOD80C       3.0
9  3003494        FUSE CRYSTAL TUBE 6,3A 5X20MM FAST       1.0

### 2.2 Definir els rols de proveïdor

Durant la formació, simularem la resposta de 3 proveïdors diferents amb personalitats diverses:

In [3]:
# Configuració de proveïdors
SUPPLIERS = {
    'DigiKey': {
        'email': 'prova@digikey.com',
        'name': 'DigiKey Electronics',
        'style': 'formal_structured',  # Respostes ben estructurades
        'response_time': '4-8 hores',
        'characteristics': [
            'Taules ben formatades',
            'Informació completa',
            'Llenguatge professional',
            'Dades precises'
        ]
    },
    'Mouser': {
        'email': 'prova@mouser.es',
        'name': 'Mouser España',
        'style': 'informal_text',  # Text lliure, més casual
        'response_time': '1-2 dies',
        'characteristics': [
            'Text en paràgrafs',
            'Estil conversacional',
            'Preguntes de seguiment',
            'Castellà informal'
        ]
    },
    'Farnell': {
        'email': 'info@farnell.com',
        'name': 'Farnell',
        'style': 'chaotic_realistic',  # Format caòtic però realista
        'response_time': '2-3 dies',
        'characteristics': [
            'Format inconsistent',
            'Abreviatures',
            'Info incompleta ocasional',
            'Estil ràpid/directe'
        ]
    }
}

print("✅ Proveïdors configurats:\n")
for name, info in SUPPLIERS.items():
    print(f"📧 {name}")
    print(f"   Email: {info['email']}")
    print(f"   Estil: {info['style']}")
    print(f"   Temps resposta: {info['response_time']}")
    print()

✅ Proveïdors configurats:

📧 DigiKey
   Email: prova@digikey.com
   Estil: formal_structured
   Temps resposta: 4-8 hores

📧 Mouser
   Email: prova@mouser.es
   Estil: informal_text
   Temps resposta: 1-2 dies

📧 Farnell
   Email: info@farnell.com
   Estil: chaotic_realistic
   Temps resposta: 2-3 dies



### 2.3 Esquemes Pydantic

Definim els models de dades estructurats que usarem:

In [4]:
from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import date

class ComponentToQuote(BaseModel):
    """Component que necessita cotització"""
    part_number: str = Field(description="Codi del component")
    description: str = Field(description="Descripció tècnica")
    quantity: int = Field(description="Quantitat necessària", gt=0)
    manufacturer: str = Field(description="Fabricant")
    priority: str = Field(description="Prioritat: high/medium/low")
    reason: str = Field(description="Per què es cotitza (car, crític, etc.)")

class QuoteRequest(BaseModel):
    """Sol·licitud de cotització (RFQ)"""
    rfq_number: str = Field(description="Número de RFQ")
    company: str = Field(description="Empresa sol·licitant")
    contact_person: str = Field(description="Persona de contacte")
    contact_email: str = Field(description="Email de contacte")
    components: List[ComponentToQuote] = Field(description="Components a cotitzar")
    notes: Optional[str] = Field(default=None, description="Notes addicionals")

class ComponentQuote(BaseModel):
    """Cotització d'un component per un proveïdor"""
    part_number: str
    supplier: str
    unit_price: float = Field(description="Preu per unitat", gt=0)
    currency: str = Field(default="EUR")
    quantity_available: Optional[int] = Field(default=None, description="Stock disponible")
    lead_time: str = Field(description="Temps de lliurament")
    moq: Optional[int] = Field(default=None, description="Minimum Order Quantity")
    valid_until: Optional[str] = Field(default=None, description="Validesa del preu")
    notes: Optional[str] = Field(default=None, description="Observacions")

class SupplierResponse(BaseModel):
    """Resposta completa d'un proveïdor"""
    supplier: str
    contact_email: str
    response_date: str
    rfq_number: str
    quotes: List[ComponentQuote]
    shipping_cost: Optional[float] = Field(default=None)
    shipping_conditions: Optional[str] = Field(default=None)
    payment_terms: Optional[str] = Field(default=None)
    additional_notes: Optional[str] = Field(default=None)

class PriceComparison(BaseModel):
    """Comparativa de preus per un component"""
    part_number: str
    description: str
    quantity_needed: int
    best_quote: ComponentQuote
    all_quotes: List[ComponentQuote]
    price_range: tuple[float, float] = Field(description="(min, max)")
    total_cost_best: float = Field(description="Cost total amb millor oferta")
    savings_vs_worst: float = Field(description="Estalvi vs pitjor oferta")
    recommendation: str
    alerts: List[str] = Field(default_factory=list)

print("✅ Esquemes Pydantic definits!")
print("\nModels disponibles:")
print("  - ComponentToQuote")
print("  - QuoteRequest")
print("  - ComponentQuote")
print("  - SupplierResponse")
print("  - PriceComparison")

✅ Esquemes Pydantic definits!

Models disponibles:
  - ComponentToQuote
  - QuoteRequest
  - ComponentQuote
  - SupplierResponse
  - PriceComparison


---
## 3. Agent 1: BOM Analyzer Expert

Aquest agent llegeix el BOM i identifica quins components cal cotitzar.

### 3.1 Tool: Read Excel BOM (reutilitzem de Part 2)

Usarem la mateixa tool que vam crear a la Part 2, però millorada:

In [5]:
from crewai.tools import tool
import pandas as pd

@tool("Read BOM Excel")
def read_bom_excel(filepath: str) -> str:
    """
    Llegeix un fitxer Excel que conté un Bill of Materials (BOM) de JCM Technologies.
    Processa el format específic de JCM amb metadata inicial i headers a la fila 7.
    
    Args:
        filepath: Ruta al fitxer Excel (ex: 'data/Bill_of_Materials-TESTBOM.xlsx')
        
    Returns:
        String amb el contingut del BOM en format llegible i detallat
    """
    try:
        # Llegir Excel saltant les primeres 6 files (metadata)
        # La fila 7 (índex 6) conté els headers
        df_bom = pd.read_excel(filepath, skiprows=7)
        
        # Filtrar només files amb MATERIAL (components reals)
        df_bom = df_bom[df_bom['MATERIAL'].notna()].copy()
        df_bom['MATERIAL'] = df_bom['MATERIAL'].astype(str).str.strip()
        df_bom['MATERIAL'] = df_bom['MATERIAL'].str.replace(r'\.0+$', '', regex=True)
        df_bom = df_bom[df_bom['MATERIAL'].str.match(r'^\d+$', na=False)].copy()
    
        if len(df_bom) == 0:
            return "ERROR: No s'han trobat components vàlids al BOM"
        
        # Netejar quantitats
        df_bom['Quantity'] = pd.to_numeric(df_bom['Quantity'], errors='coerce').fillna(1).astype(int)
        
        # Generar output detallat
        output = f"BOM REAL DE JCM TECHNOLOGIES (TESTBOM)\n"
        output += f"Llegit de: {filepath}\n\n"
        output += f"═" * 80 + "\n"
        output += f"RESUM GENERAL\n"
        output += f"═" * 80 + "\n"
        output += f"Total de components diferents: {len(df_bom)}\n"
        output += f"Total d'unitats necessàries: {df_bom['Quantity'].sum()}\n"
        
        # Categoritzar components per tipus
        def get_category(desc):
            if pd.isna(desc):
                return 'Unknown'
            desc_lower = str(desc).lower()
            if 'diode' in desc_lower:
                if 'led' in desc_lower:
                    return 'LED'
                elif 'zener' in desc_lower:
                    return 'Diode-Zener'
                elif 'schottky' in desc_lower:
                    return 'Diode-Schottky'
                else:
                    return 'Diode'
            elif 'cap' in desc_lower or 'capacitor' in desc_lower:
                if 'alum' in desc_lower or 'electrolytic' in desc_lower:
                    return 'Capacitor-Electrolytic'
                return 'Capacitor-Ceramic'
            elif 'res' in desc_lower or 'resistor' in desc_lower:
                return 'Resistor'
            elif 'ic ' in desc_lower or 'mcu' in desc_lower:
                return 'IC'
            elif 'relay' in desc_lower or 'relé' in desc_lower:
                return 'Relay'
            elif 'trans' in desc_lower:
                if 'former' in desc_lower:
                    return 'Transformer'
                return 'Transistor'
            elif 'switch' in desc_lower:
                return 'Switch'
            elif 'buzzer' in desc_lower:
                return 'Buzzer'
            elif 'fuse' in desc_lower:
                return 'Fuse/Protection'
            else:
                return 'Other'
        
        df_bom['Category'] = df_bom['Description'].apply(get_category)
        
        output += f"\nComponents per categoria:\n"
        category_counts = df_bom['Category'].value_counts()
        for cat, count in category_counts.items():
            output += f"  - {cat}: {count} components\n"
        
        output += f"\n" + "═" * 80 + "\n"
        output += f"DETALL DELS COMPONENTS\n"
        output += f"═" * 80 + "\n\n"
        
        for idx, (_, row) in enumerate(df_bom.iterrows(), 1):
            output += f"Component {idx}. Part Number: {row['MATERIAL']}\n"
            output += f"   Descripció: {row['Description']}\n"
            output += f"   Quantitat: {row['Quantity']} pcs\n"
            output += f"   Categoria: {row['Category']}\n"
            output += f"   {'-' * 76}\n"
        
        return output
        
    except FileNotFoundError:
        return f"ERROR: No s'ha trobat el fitxer {filepath}"
    except KeyError as e:
        return f"ERROR: No s'ha trobat la columna esperada: {e}\n\nEl BOM de JCM ha de tenir columnes: MATERIAL, Description, Quantity"
    except Exception as e:
        return f"ERROR llegint el fitxer: {str(e)}\n\nDetalls: El BOM de JCM té un format específic amb metadata a les primeres 6 files i headers a la fila 7."

print("✅ Tool 'read_bom_excel' creada (processament format JCM)!")

✅ Tool 'read_bom_excel' creada (processament format JCM)!


### 3.2 Crear l'Agent BOM Analyzer

In [6]:
from crewai import Agent
from dotenv import load_dotenv

load_dotenv(override=True)

agent_bom_analyzer = Agent(
    role="Expert Analitzador de BOMs",
    goal="Analitzar BOMs i identificar components que necessiten cotització prioritària",
    backstory="""
    Ets un enginyer electrònic senior amb 20 anys d'experiència a JCM Technologies.
    
    La teva especialitat és analitzar Bills of Materials i identificar:
    
    **Components que cal cotitzar amb prioritat:**
    - Components cars (ICs, relés, PCBs customitzades)
    - Components crítics per al funcionament
    - Components amb lead times potencialment llargs
    - Components amb quantitats grans
    
    **No cal cotitzar:**
    - Components passius bàsics i econòmics (resistències, condensadors petits)
    - Components amb cost unitari molt baix (<€0.10)
    
    Tens accés a eines per llegir fitxers Excel amb BOMs.
    
    El teu anàlisi és sempre tècnic, precís i ben prioritzat.
    Proporcionas llistes clares amb justificació de cada decisió.
    """,
    tools=[read_bom_excel],
    llm=OPENAI_MODEL,
    verbose=True
)

print("✅ Agent 'BOM Analyzer' creat!")

✅ Agent 'BOM Analyzer' creat!


### 3.3 Task per l'Agent BOM Analyzer

In [7]:
from crewai import Task

task_analyze_bom = Task(
    description="""
    Analitza el BOM REAL de JCM del fitxer 'data/Bill_of_Materials-TESTBOM.xlsx'.
    
    Has de:
    1. Llegir el fitxer Excel amb la tool disponible
    2. DISTRIBUIR els components segons especialització del proveïdor:
    
       **DigiKey (especialista en ICs i electrònica digital):**
       - Microcontroladors (MCU)
       - ICs (reguladors de voltatge, etc.)
       - Tots els altres components que no siguin específics d'altres proveïdors
       
       **Farnell (especialista en components de potència):**
       - Relés
       - Transformers
       - Tots els altres components que no siguin específics d'altres proveïdors
       
       **Mouser (especialista en semiconductors discrets):**
       - Díodes (tots els tipus: Schottky, Zener, LEDs, rectificadors)
       - Transistors
       - Tots els altres components que no siguin específics d'altres proveïdors
    
    3. Prioritzar per:
       - Cost estimat (ICs, relés, transformers > LEDs, díodes > resistències)
       - Criticitat per al funcionament (MCU, regulador, relay són crítics)
       - Quantitat necessària (més quantitat = més prioritat)
    4. Per cada component seleccionat, proporciona:
       - Part Number EXACTE (el codi MATERIAL com apareix al BOM)
       - Descripció completa
       - Quantitat necessària
       - Prioritat (high/medium/low)
       - Raó per cotitzar-lo
    
    PRIORITATS RECOMANADES per components JCM:
    - HIGH: IC MCU (PIC16F), IC regulador (L7805), Relay, Transformer
    - MEDIUM: Transistors (si quantitat >2), Switches, Buzzer, Díodes Schottky/Zener
    - LOW: LEDs, Díodes 1N4148, Fuses
    
    NO incloguis:
    - Resistències (massa econòmiques)
    - Condensadors ceràmics petits (econòmics)
    
    IMPORTANT: Els part numbers han de ser EXACTES (els codis de 7 dígits com 3005688).
    """,
    expected_output="""
    Una llista estructurada de tots components amb aquest format per cada un:
    
    ## Component [número]
    - **Part Number:** [codi exacte del BOM]
    - **Descripció:** [descripció completa]
    - **Quantitat:** [número]
    - **Fabricant:** [nom]
    - **Prioritat:** [high/medium/low]
    - **Raó:** [per què cal cotitzar-lo]
    
    Al final, un resum:
    ## Resum
    - Total components a cotitzar: [número]
    - Prioritat high: [número]
    - Prioritat medium: [número]
    - Prioritat low: [número]
    """,
    agent=agent_bom_analyzer
)

print("✅ Task 'Analyze BOM' creada!")

✅ Task 'Analyze BOM' creada!


### 3.4 Provar l'Agent BOM Analyzer

Executem aquest primer agent per veure què identifica:

In [8]:
from crewai import Crew

# Crew temporal només amb aquest agent
crew_test_analyzer = Crew(
    agents=[agent_bom_analyzer],
    tasks=[task_analyze_bom],
    process=Process.sequential,
    verbose=True
)

print("🚀 Executant Agent BOM Analyzer...\n")
print("=" * 70)

result_analyzer = crew_test_analyzer.kickoff()

print("\n" + "=" * 70)
print("✅ Anàlisi completada!\n")
print("📋 COMPONENTS IDENTIFICATS PER COTITZAR:\n")
print(result_analyzer)

🚀 Executant Agent BOM Analyzer...



╭──────────────────────────────────────────── Crew Execution Started ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Started                                                                                         │
│  Name: crew                                                                                                     │
│  ID: c15bce32-3339-4795-9167-a56f3a90bf85                                                                       │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert Analitzador de BOMs                                                                              │
│                                                                                                                 │
│  Task:                                                                                                          │
│      Analitza el BOM REAL de JCM del fitxer 'data/Bill_of_Materials-TESTBOM.xlsx'.                              │
│                                                                                                                 │
│      Has de:                                                                                                    │
│      1. Llegir el fitxer Excel amb la tool disponible                                                           │
│      2. DISTRIBUIR els components segons especialització del proveïdor:                                         │
│                                                                                                                 │
│         **DigiKey (especialista en ICs i electrònica digital):**                                                │
│         - Microcontroladors (MCU)                                                                               │
│         - ICs (reguladors de voltatge, etc.)                                                                    │
│         - Tots els altres components que no siguin específics d'altres proveïdors                               │
│                                                                                                                 │
│         **Farnell (especialista en components de potència):**                                                   │
│         - Relés                                                                                                 │
│         - Transformers                                                                                          │
│         - Tots els altres components que no siguin específics d'altres proveïdors                               │
│                                                                                                                 │
│         **Mouser (especialista en semiconductors discrets):**                                                   │
│         - Díodes (tots els tipus: Schottky, Zener, LEDs, rectificadors)                                         │
│         - Transistors                                                                                           │
│         - Tots els altres components que no siguin específics d'altres proveïdors                               │
│                                                                                                                 │
│      3. Prioritzar per:                                                                                         │
│         - Cost estimat (ICs, relés, transformers > LEDs, díodes > resistències)                                 │
│         - Criticitat per al funcionament (MCU, regulador, relay són crítics)                                    │
│         - Quantitat necessària (més quantitat = més prioritat)                                                  │
│      4. Per cada component seleccionat, proporciona:                                                            │
│         - Part Number EXACTE (el codi MATERIAL com apareix al BOM)                                              │
│         - Descripció completa                                                                                   │
│         - Quantitat necessària                                                                                  │
│         - Prioritat (high/medium/low)                  

Output()

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert Analitzador de BOMs                                                                              │
│                                                                                                                 │
│  Thought: He de llegir el fitxer Excel que conté el BOM per analitzar els components i distribuir-los segons    │
│  les especificacions dels proveïdors.                                                                           │
│                                                                                                                 │
│  Using Tool: Read BOM Excel                                                                                     │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert Analitzador de BOMs                                                                              │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  ## Component 1                                                                                                 │
│  - **Part Number:** 3005688                                                                                     │
│  - **Descripció:** IC MCU PIC16F18855T-I/SS 8BIT 8KB FLASH                                                      │
│  - **Quantitat:** 1 pcs                                                                                         │
│  - **Fabricant:** JCM Technologies                                                                              │
│  - **Prioritat:** high                                                                                          │
│  - **Raó:** Component crític per al funcionament del sistema.                                                   │
│                                                                                                                 │
│  ## Component 2                                                                                                 │
│  - **Part Number:** 3000836                                                                                     │
│  - **Descripció:** IC VOLTAGE REG LDO 5V L7805ABD SMD SO8                                                       │
│  - **Quantitat:** 1 pcs                                                                                         │
│  - **Fabricant:** JCM Technologies                                                                              │
│  - **Prioritat:** high                                                                                          │
│  - **Raó:** Component crític per al funcionament del sistema.                                                   │
│                                                                                                                 │
│  ## Component 3                                                                                                 │
│  - **Part Number:** 3003060                                                                                     │
│  - **Descripció:** TRANSFORMER 230VAC 12VAC 2,8VA TH                                                            │
│  - **Quantitat:** 1 pcs                                                                                         │
│  - **Fabricant:** JCM Technologies                                                                              │
│  - **Prioritat:** high                                                                                          │
│  - **Raó:** Component crític per al funcionament del sistema.                                                   │
│                                                                                                                 │
│  ## Component 4                                                                                                 │
│  - **Part Number:** 3003026                                                                                     │
│  - **Descripció:** RELAY GENERAL PURPOSE DPDT 12V TH                                                            │
│  - **Quantitat:** 2 pcs                                                                                         │
│  - **Fabricant:** JCM Technologies                                                                              │
│  - **Prioritat:** high                                 

Output()

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: 4f616849-8807-4d6b-8c6a-5d5bc6c5774c                                                                     │
│  Agent: Expert Analitzador de BOMs                                                                              │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


✅ Anàlisi completada!

📋 COMPONENTS IDENTIFICATS PER COTITZAR:

## Component 1
- **Part Number:** 3005688
- **Descripció:** IC MCU PIC16F18855T-I/SS 8BIT 8KB FLASH
- **Quantitat:** 1 pcs
- **Fabricant:** JCM Technologies
- **Prioritat:** high
- **Raó:** Component crític per al funcionament del sistema.

## Component 2
- **Part Number:** 3000836
- **Descripció:** IC VOLTAGE REG LDO 5V L7805ABD SMD SO8
- **Quantitat:** 1 pcs
- **Fabricant:** JCM Technologies
- **Prioritat:** high
- **Raó:** Component crític per al funcionament del sistema.

## Component 3
- **Part Number:** 3003060
- **Descripció:** TRANSFORMER 230VAC 12VAC 2,8VA TH
- **Quantitat:** 1 pcs
- **Fabricant:** JCM Technologies
- **Prioritat:** high
- **Raó:** Component crític per al funcionament del sistema.

## Component 4
- **Part Number:** 3003026
- **Descripció:** RELAY GENERAL PURPOSE DPDT 12V TH
- **Quantitat:** 2 pcs
- **Fabricant:** JCM Technologies
- **Prioritat:** high
- **Raó:** Component crític per al funcionamen

╭──────────────────────────────────────────────── Crew Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Completed                                                                                       │
│  Name: crew                                                                                                     │
│  ID: c15bce32-3339-4795-9167-a56f3a90bf85                                                                       │
│  Tool Args:                                                                                                     │
│  Final Output: ## Component 1                                                                                   │
│  - **Part Number:** 3005688                                                                                     │
│  - **Descripció:** IC MCU PIC16F18855T-I/SS 8BIT 8KB FLASH                                                      │
│  - **Quantitat:** 1 pcs                                                                                         │
│  - **Fabricant:** JCM Technologies                                                                              │
│  - **Prioritat:** high                                                                                          │
│  - **Raó:** Component crític per al funcionament del sistema.                                                   │
│                                                                                                                 │
│  ## Component 2                                                                                                 │
│  - **Part Number:** 3000836                                                                                     │
│  - **Descripció:** IC VOLTAGE REG LDO 5V L7805ABD SMD SO8                                                       │
│  - **Quantitat:** 1 pcs                                                                                         │
│  - **Fabricant:** JCM Technologies                                                                              │
│  - **Prioritat:** high                                                                                          │
│  - **Raó:** Component crític per al funcionament del sistema.                                                   │
│                                                                                                                 │
│  ## Component 3                                                                                                 │
│  - **Part Number:** 3003060                                                                                     │
│  - **Descripció:** TRANSFORMER 230VAC 12VAC 2,8VA TH                                                            │
│  - **Quantitat:** 1 pcs                                                                                         │
│  - **Fabricant:** JCM Technologies                                                                              │
│  - **Prioritat:** high                                                                                          │
│  - **Raó:** Component crític per al funcionament del sistema.                                                   │
│                                                                                                                 │
│  ## Component 4                                                                                                 │
│  - **Part Number:** 3003026                                                                                     │
│  - **Descripció:** RELAY GENERAL PURPOSE DPDT 12V TH                                                            │
│  - **Quantitat:** 2 pcs                                                                                         │
│  - **Fabricant:** JCM Technologies                    

╭──────────────────────────────────────────────── Tracing Status ─────────────────────────────────────────────────╮
│                                                                                                                 │
│  Info: Tracing is disabled.                                                                                     │
│                                                                                                                 │
│  To enable tracing, do any one of these:                                                                        │
│  • Set tracing=True in your Crew/Flow code                                                                      │
│  • Set CREWAI_TRACING_ENABLED=true in your project's .env file                                                  │
│  • Run: crewai traces enable                                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


### 💡 Observa el resultat

L'agent hauria d'haver identificat components com:

**✅ PRIORITAT HIGH (crítics i cars):**
- **3005688** - IC MCU PIC16F18855 (microcontrolador, el "cervell" del sistema)
- **3000836** - IC regulador L7805ABD (estabilitat alimentació crítica)
- **3003026** - Relay DPDT 12V (x2 unitats, control de potència)
- **3003060** - Transformer 230VAC→12VAC (alimentació principal)

**✅ PRIORITAT MEDIUM (importants):**
- **3003807** - Transistor NPN BC847B (x4 unitats, quantitat elevada)
- **3003808** - Transistor PNP BC857B/T1
- **3003413/3003412** - Switches tàctils (interfície usuari)
- **3003522** - Buzzer magnètic (senyalització)
- **3003780** - Díode Schottky BAT54A (velocitat crítica)
- **3003681** - Díode Zener BZT55C (protecció voltatge)
- **3003737** - Díode rectificador pont AM156 (alimentació)

**✅ PRIORITAT LOW (funcionals però econòmics):**
- **3003775/3003762** - LEDs indicadors (verd/vermell)
- **3003669** - Díodes 1N4148 (x3, ús general)
- **3003494** - Fusible cristall 6.3A
- **3003506/3003504** - Portafusibles

**❌ NO inclosos (massa econòmics):**
- Resistències SMD (3003913, 3003925, 3000151) 
- Condensadors ceràmics petits (3000598)

**Aquest output serà l'input del següent agent!**

**Aquest output serà l'input del següent agent!**

---
## 4. Agent 2: RFQ Generator

Aquest agent genera emails professionals (RFQ - Request for Quotation) per enviar als proveïdors.

### 4.1 Què és un RFQ?

**RFQ (Request for Quotation)** és un document formal que s'envia als proveïdors sol·licitant preus.

**Components d'un bon RFQ:**
- ✅ Dades de l'empresa
- ✅ Persona de contacte
- ✅ Llista detallada de components (Part Number, descripció, quantitat)
- ✅ Informació tècnica rellevant
- ✅ Data límit de resposta (opcional)
- ✅ Condicions de pagament preferides (opcional)
- ✅ To professional però amigable

### 4.2 Tool: Format RFQ Email

Aquesta tool ajuda a formatar l'email de manera professional:

In [9]:
@tool("Format RFQ Email")
def format_rfq_email(
    supplier_name: str,
    supplier_email: str,
    components_list: str,
    rfq_number: str
) -> str:
    """
    Formata un email RFQ professional per enviar a un proveïdor.
    
    Args:
        supplier_name: Nom del proveïdor (ex: 'DigiKey')
        supplier_email: Email del proveïdor
        components_list: Llista de components en format text
        rfq_number: Número de referència del RFQ
        
    Returns:
        Email formatat professionalment
    """
    from datetime import datetime
    
    today = datetime.now().strftime("%d/%m/%Y")
    
    email_template = f"""
══════════════════════════════════════════════════════════════════════
EMAIL RFQ - {rfq_number}
══════════════════════════════════════════════════════════════════════

De: compras@jcmtechnologies.com
Per a: {supplier_email}
Assumpte: Sol·licitud de cotització #{rfq_number} - Components electrònics
Data: {today}

──────────────────────────────────────────────────────────────────────

Benvolgut/da equip de {supplier_name},

Des de JCM Technologies, SAU, volem sol·licitar-vos una cotització per 
als següents components electrònics per a un projecte de control de portes 
automàtiques.

COMPONENTS SOL·LICITATS:
──────────────────────────────────────────────────────────────────────

{components_list}

──────────────────────────────────────────────────────────────────────

INFORMACIÓ ADDICIONAL:

- Referència RFQ: {rfq_number}
- Data límit resposta: {(datetime.now() + pd.Timedelta(days=7)).strftime("%d/%m/%Y")}
- Lliurament preferit: Vic, Barcelona, Espanya
- Condicions de pagament: 30 dies data factura

Us agrairíem que ens proporcionéssiu:
✓ Preu unitari per component
✓ Disponibilitat de stock actual
✓ Temps de lliurament estimat
✓ MOQ (Minimum Order Quantity) si aplica
✓ Validesa de la cotització

Qualsevol dubte sobre especificacions tècniques, no dubteu en contactar-nos.

Atentament,

Departament de Compres
JCM Technologies, SAU
Tel: +34 938 03 XX XX
Email: compras@jcmtechnologies.com
Web: www.jcmtechnologies.com

══════════════════════════════════════════════════════════════════════
"""
    
    return email_template

print("✅ Tool 'format_rfq_email' creada!")

✅ Tool 'format_rfq_email' creada!


### 4.3 Crear l'Agent RFQ Generator

In [10]:
agent_rfq_generator = Agent(
    role="Especialista en Generació de RFQs",
    goal="Generar emails RFQ professionals i complets per sol·licitar cotitzacions a proveïdors",
    backstory="""
    Ets un expert en generar sol·licituds de cotització (RFQs) per components electrònics.
    
    REGLA D'OR: SEMPRE uses els part numbers EXACTES que reps del context.
    MAI inventes part numbers. MAI modifiques part numbers.
    
    Si un component té el part number 3003413, uses 3003413.
    Si un component té el part number 3003522, uses 3003522.
    
    La teva tasca és distribuir els components analitzats entre els 3 proveïdors
    segons les seves especialitats, mantenint SEMPRE els part numbers originals.
    
    Tens accés a una tool per formatar emails RFQ professionals.
    """,
    tools=[format_rfq_email],
    llm=OPENAI_MODEL,
    max_iter=5,
    verbose=True
)

print("✅ Agent 'RFQ Generator' creat!")

✅ Agent 'RFQ Generator' creat!


### 4.4 Task per l'Agent RFQ Generator

In [11]:
task_generate_rfqs = Task(
    description="""
    Genera 3 RFQs (DigiKey, Mouser, Farnell) basant-te ESTRICTAMENT en l'anàlisi del BOM.
    
    CRÍTIC - USA NOMÉS PART NUMBERS DEL CONTEXT:
    - NO inventis part numbers
    - NO modifiquis part numbers
    - USA EXACTAMENT els part numbers que l'agent anterior ha analitzat
    
    Del context (task anterior), tens la llista de components prioritaris amb:
    - Part Number EXACTE
    - Descripció
    - Quantitat
    
    Distribueix aquests components entre els 3 proveïdors segons l'especialitat:
    
    DIGIKEY (ICs i digital):
    - Tots els ICs (MCU, reguladors)
    - Switches
    - Buzzer
    - Fusibles
    
    MOUSER (Semiconductors discrets):
    - Tots els díodes (Schottky, Zener, LEDs, rectificadors)
    - Tots els transistors
    
    FARNELL (Potència):
    - Relays
    - Transformers
    
    PER CADA PROVEÏDOR, genera un email RFQ professional.
    
    IMPORTANT: Cada component ha d'aparèixer amb el seu Part Number EXACTE del BOM.
    """,
    expected_output="""
    3 RFQs professionals, un per cada proveïdor.
    
    Cada RFQ ha de contenir:
    - Destinatari (email del proveïdor)
    - Assumpte
    - Cos de l'email amb:
      * Components amb Part Number EXACTE del BOM
      * Descripció
      * Quantitat
      * Informació addicional (RFQ-2025-001, data límit, etc.)
    
    Format:
    ## RFQ per DigiKey
    [contingut email complet]
    
    ## RFQ per Mouser
    [contingut email complet]
    
    ## RFQ per Farnell
    [contingut email complet]
    """,
    agent=agent_rfq_generator,
    context=[task_analyze_bom]  # ← Rep l'output de l'agent anterior
)

print("✅ Task 'Generate RFQs' creada amb distribució intel·ligent per proveïdor!")
print("\n💡 Distribució de components per especialitat:")
print("   - DigiKey: ICs i microcontroladors + components comuns")
print("   - Mouser: Díodes i transistors + components comuns")
print("   - Farnell: Relés i transformers + components comuns")
print("\n   Components comuns (switches, buzzer, fusibles): TOTS els proveïdors")

✅ Task 'Generate RFQs' creada amb distribució intel·ligent per proveïdor!

💡 Distribució de components per especialitat:
   - DigiKey: ICs i microcontroladors + components comuns
   - Mouser: Díodes i transistors + components comuns
   - Farnell: Relés i transformers + components comuns

   Components comuns (switches, buzzer, fusibles): TOTS els proveïdors


---
## 5. Enviar Emails REALS amb Gmail API

Ara ve la part emocionant: **enviarem emails REALS** amb els RFQs generats!

### 5.1 Tool: Authenticate Gmail

Primer creem una tool per autenticar amb Gmail:

In [12]:
import os
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

# Permisos necessaris
SCOPES = [
    'https://www.googleapis.com/auth/gmail.send',      # Enviar emails
    'https://www.googleapis.com/auth/gmail.readonly',  # Llegir emails
    'https://www.googleapis.com/auth/gmail.modify'     # Marcar com llegit
]

def authenticate_gmail():
    """
    Autentica amb Gmail API i retorna el servei.
    
    Returns:
        Gmail API service object
    """
    creds = None
    
    # Si ja existeix token.json, el carrega
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    
    # Si no hi ha credencials vàlides, autentica
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            print("🔄 Renovant token...")
            creds.refresh(Request())
        else:
            if not os.path.exists('credentials.json'):
                raise FileNotFoundError(
                    "❌ No s'ha trobat credentials.json!\n"
                    "Segueix les instruccions de la secció 5.1 per crear-lo."
                )
            
            print("🔐 Primera autenticació...")
            print("   S'obrirà un navegador per autenticar-te.")
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES
            )
            creds = flow.run_local_server(port=0)
        
        # Guardar credencials per següents vegades
        with open('token.json', 'w') as token:
            token.write(creds.to_json())
        print("✅ Token guardat a token.json")
    
    # Crear servei Gmail
    service = build('gmail', 'v1', credentials=creds)
    
    # Obtenir info del compte
    profile = service.users().getProfile(userId='me').execute()
    print(f"✅ Autenticat com: {profile['emailAddress']}")
    
    return service

print("✅ Funció authenticate_gmail() definida")

✅ Funció authenticate_gmail() definida


### 5.2 Provar autenticació

Executem per autenticar-nos i verificar que funciona:

In [ ]:
# Autenticar (primera vegada obrirà navegador)
try:
    gmail_service = authenticate_gmail()
    print("\n✅ Gmail API configurada correctament!")
    print("Ja pots enviar i rebre emails programàticament.")
except FileNotFoundError as e:
    print(f"\n❌ Error: {e}")
    print("\n📋 Accions necessàries:")
    print("1. Segueix les instruccions de la secció 5.1")
    print("2. Descarrega credentials.json")
    print("3. Col·loca'l a la carpeta del projecte")
    print("4. Torna a executar aquesta cel·la")
except Exception as e:
    print(f"\n❌ Error inesperat: {e}")

### 5.3 Tool: Send Email

Ara creem la tool per enviar emails:

In [13]:
from email.mime.text import MIMEText
import base64
from crewai.tools import tool

@tool("Send Email via Gmail")
def send_email_gmail(
    to_email: str,
    subject: str,
    body: str
) -> str:
    """
    Envia un email via Gmail API.
    
    Args:
        to_email: Email destinatari (ex: 'colleague@jcm-tech.com')
        subject: Assumpte de l'email
        body: Cos del missatge (text pla)
        
    Returns:
        Confirmació de l'enviament amb ID del missatge
    """
    try:
        # Autenticar
        service = authenticate_gmail()
        
        # Crear missatge
        message = MIMEText(body)
        message['to'] = to_email
        message['subject'] = subject
        
        # Codificar en base64
        raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode('utf-8')
        
        # Enviar
        sent_message = service.users().messages().send(
            userId='me',
            body={'raw': raw_message}
        ).execute()
        
        result = f"""
✅ EMAIL ENVIAT AMB ÈXIT!

Destinatari: {to_email}
Assumpte: {subject}
ID del missatge: {sent_message['id']}

L'email ha estat enviat correctament via Gmail.
"""
        return result
        
    except Exception as e:
        return f"❌ ERROR enviant email: {str(e)}"

print("✅ Tool 'send_email_gmail' creada!")

✅ Tool 'send_email_gmail' creada!


### 5.4 Tool: Fetch Emails

Tool per llegir emails rebuts:

In [14]:
@tool("Fetch Emails from Gmail")
def fetch_emails_gmail(
    query: str = "is:unread",
    max_results: int = 10
) -> str:
    """
    Llegeix emails de la inbox de Gmail.
    
    Args:
        query: Cerca Gmail (ex: 'is:unread subject:RFQ', 'from:colleague@company.com')
        max_results: Màxim d'emails a retornar (default: 10)
        
    Returns:
        Llista d'emails amb: From, Subject, Date, Body
    """
    try:
        # Autenticar
        service = authenticate_gmail()
        
        # Cercar missatges
        results = service.users().messages().list(
            userId='me',
            q=query,
            maxResults=max_results
        ).execute()
        
        messages = results.get('messages', [])
        
        if not messages:
            return f"ℹ️ No s'han trobat emails que coincideixin amb: '{query}'"
        
        output = f"📧 S'han trobat {len(messages)} email(s):\n\n"
        output += "=" * 80 + "\n\n"
        
        for idx, msg in enumerate(messages, 1):
            # Obtenir detalls del missatge
            msg_data = service.users().messages().get(
                userId='me',
                id=msg['id'],
                format='full'
            ).execute()
            
            # Extreure headers
            headers = msg_data['payload']['headers']
            subject = next((h['value'] for h in headers if h['name'] == 'Subject'), 'Sin asunto')
            from_email = next((h['value'] for h in headers if h['name'] == 'From'), 'Desconocido')
            date = next((h['value'] for h in headers if h['name'] == 'Date'), 'Fecha desconocida')
            
            # Extreure cos del missatge
            body = ""
            if 'parts' in msg_data['payload']:
                for part in msg_data['payload']['parts']:
                    if part['mimeType'] == 'text/plain':
                        if 'data' in part['body']:
                            body = base64.urlsafe_b64decode(
                                part['body']['data']
                            ).decode('utf-8')
                            break
            else:
                if 'data' in msg_data['payload']['body']:
                    body = base64.urlsafe_b64decode(
                        msg_data['payload']['body']['data']
                    ).decode('utf-8')
            
            output += f"EMAIL {idx}\n"
            output += "-" * 80 + "\n"
            output += f"De: {from_email}\n"
            output += f"Assumpte: {subject}\n"
            output += f"Data: {date}\n"
            output += f"ID: {msg['id']}\n"
            output += "-" * 80 + "\n"
            output += f"COS DEL MISSATGE:\n\n{body[:1000]}"  # Limitar a 1000 caràcters
            if len(body) > 1000:
                output += "\n\n[... missatge truncat ...]\n"
            output += "\n" + "=" * 80 + "\n\n"
        
        return output
        
    except Exception as e:
        return f"❌ ERROR llegint emails: {str(e)}"

print("✅ Tool 'fetch_emails_gmail' creada!")

✅ Tool 'fetch_emails_gmail' creada!


### 5.5 Provar les tools manualment

Abans de donar-les als agents, provem que funcionen:

In [ ]:
# OPCIONAL: Prova d'enviament (canvia l'email!)
# Descomenta i executa si vols provar

#test_result = send_email_gmail._run(
#     to_email="jberingues@jcm-tech.com",  # ← Canvia això!
#     subject="Test CrewAI Gmail Integration",
#     body="Hola! Aquest és un email de prova enviat des de CrewAI.\n\nFunciona! 🎉"
# )
#print(test_result)

print("\n💡 Per provar l'enviament, descomenta el codi de dalt i executa.")
print("   Recorda canviar 'teu_email@gmail.com' pel teu email real!")

In [ ]:
# Provar lectura d'emails
print("📬 Llegint emails recents...\n")

emails = fetch_emails_gmail._run(
    query="newer_than:1d",  # Emails de les últimes 24h
    max_results=3
)

print(emails)

---
## 6. Dinàmica de la Formació: Enviar i Respondre

Ara ve la part interactiva! Cada assistent enviarà i rebrà un RFQ.

### 6.1 Dinàmica amb 3 Voluntaris

**🎭 Dinàmica de la formació:**

Com que el sistema complet s'executarà amb **OpenAI** (per evitar problemes de quota), farem una **demostració interactiva** amb participació de l'audiència:

```
📊 WORKFLOW:

1. Jo (formador) executo el sistema fins generar els 3 RFQs
2. El sistema ENVIA els RFQs per Gmail als 3 voluntaris:
   - Voluntari 1 → Rep RFQ de DigiKey
   - Voluntari 2 → Rep RFQ de Mouser  
   - Voluntari 3 → Rep RFQ de Farnell
3. Els 3 voluntaris responen (10-15 min)
4. Jo executo la resta del sistema que:
   - Llegeix les 3 respostes
   - Les parseja automàticament
   - Compara preus
   - Genera informe executiu
5. Tothom veu l'informe final generat
```

**📋 Rols dels voluntaris:**

```
VOLUNTARI 1: DigiKey
  - Rebràs un RFQ amb components d'ICs i digital
  - Respon amb format: Taula estructurada (professional)
  - Estil: Formal i organitzat

VOLUNTARI 2: Mouser
  - Rebràs un RFQ amb díodes i transistors
  - Respon amb format: Text lliure conversacional
  - Estil: Friendly i informal

VOLUNTARI 3: Farnell
  - Rebràs un RFQ amb relés i transformers
  - Respon amb format: Caòtic/realista
  - Estil: Desorganitzat però amb info útil
```

**⏱️ Timing:**
- Enviar RFQs: 2 min
- Voluntaris responen: 10-15 min
- Processar respostes + informe: 3-5 min
- **Total:** ~20 min

### 6.2 Templates de resposta per als 3 voluntaris

**💡 Instruccions per als voluntaris:**

Quan rebeu l'email RFQ, **utilitzeu el template corresponent al vostre rol** com a guia, però:
- ✅ Podeu canviar preus lleugerament (±10-20%)
- ✅ Podeu afegir o treure alguna línia
- ✅ Podeu personalitzar l'estil

**L'objectiu:** Que cada resposta sigui realista i lleugerament diferent.

In [15]:
# ═══════════════════════════════════════════════════════════════════════════
# TEMPLATES DE RESPOSTA AMB COMPONENTS REALS DEL BOM JCM
# ═══════════════════════════════════════════════════════════════════════════

TEMPLATE_DIGIKEY = """
De: sales@digikey.com
Assumpte: RE: Sol·licitud de cotització #RFQ-2025-001

Benvolgut/da,

Gràcies per la vostra consulta. Us adjunto la cotització dels components sol·licitats:

Part Number | Description                              | Qty | Unit Price | Stock    | Lead Time
------------|------------------------------------------|-----|------------|----------|----------
3005688     | IC MCU PIC16F18855T-I/SS 8BIT 8KB FLASH | 1   | €2.85      | 1000+ pcs| 2 dies
3000836     | IC VOLTAGE REG LDO 5V L7805ABD SMD SO8  | 1   | €0.45      | 500+ pcs | 1 setmana
3003413     | TACT SWITCH SPST-NO 6X6 LOW TH          | 1   | €0.18      | 2000+ pcs| 3 dies
3003412     | TACT SWITCH SPST-NO 6X6MM RAISED RED TH | 1   | €0.22      | 1500+ pcs| 3 dies
3003522     | BUZZER MAG 2KHZ 1.5VDC 12MM EXTERNALTH  | 1   | €0.95      | 300+ pcs | 5 dies
3003494     | FUSE CRYSTAL TUBE 6,3A 5X20MM FAST      | 1   | €0.12      | 5000+ pcs| 2 dies

Condicions comercials:
- Preus vàlids fins: 15/02/2026
- MOQ: 10 unitats per component
- Enviament: €25 (gratuït per comandes >€500)
- Termini de pagament: 30 dies net
- Descompte per volum disponible (consultar)

Salutacions cordials,
DigiKey Sales Team
sales@digikey.com
"""

TEMPLATE_MOUSER = """
De: ventas@mouser.es
Assumpte: Cotización - Componentes electrónicos JCM Technologies

Hola,

He revisado tu solicitud de cotización y te comento lo que tenemos disponible:

Para los díodes que necesitas, tenemos bastante stock. El díode Schottky BAT54A 
(ref 3003780) está a 0,15€ por unidad, tenemos unas 2000 unidades en stock 
y te lo podemos enviar en 2-3 días. Los díodes Zener BZT55C 5V6 (3003681) 
van a 0,08€ cada uno, también con disponibilidad inmediata.

Los LEDs verde y rojo (3003775 y 3003762) están a buen precio: 0,12€ el verde 
y 0,10€ el rojo. Tenemos bastante stock de ambos, unas 5000 unidades de cada.

Para los transistores BC847B (ref 3003807) que pides 4 unidades, el precio 
es de 0,06€/ud. Los BC857B (3003808) van a 0,07€. Stock suficiente de ambos.

El díode rectificador de puente AM156 (3003737) lo tenemos a 0,35€ y los 
díodes 1N4148 (3003669) a 0,04€ cada uno.

Los plazos de entrega son normalmente de 3-5 días laborables para península.
Portes: 15€ (gratis si superas 200€ de pedido).

¿Necesitas algo más? Cualquier duda me comentas.

Saludos,
Carlos Martínez
Mouser España
ventas@mouser.es
"""

TEMPLATE_FARNELL = """
De: info@farnell.com
Assumpte: Re: Presupuesto componentes

Buenos días,

RELAY DPDT 12V ref 3003026: 2,85€/ud tenemos 180ud STOCK OK!!! 
Entrega 24-48h península

TRANSFORMER 230VAC→12VAC 2.8VA (3003060) -> precio 4.50 EUR 
stock: 45 pcs, lead time 1 semana aprox

Switches tactiles:
- 3003413 (6x6 LOW): 0.19€ 
- 3003412 (6x6 RAISED RED): 0.24€
Stock ambos OK (2000+ uds)

Buzzer 3003522: 0,98€ tenemos 250ud entrega inmediata

Fusible 6,3A ref 3003494 -> 0,11 EUR stock SI!!! 8000pcs
Portafusibles 3003506: 0,35€ (3000 uds disponibles)

Todos los precios SIN IVA
Portes: 18€ (pedidos >350€ portes gratis)
Forma pago: transferencia 30 días o tarjeta

Saludos
Dpto. Ventas Farnell
info@farnell.com
"""

print("=" * 80)
print("📋 TEMPLATES DE RESPOSTA AMB COMPONENTS REALS JCM")
print("=" * 80)
print()
print("✅ 3 templates creats amb components del BOM TESTBOM:")
print()
print("1️⃣  TEMPLATE_DIGIKEY")
print("   • Format: Taula estructurada (professional)")
print("   • Components: ICs, Switches, Buzzer, Fuse")
print("   • Estil: Formal i organitzat")
print()
print("2️⃣  TEMPLATE_MOUSER")
print("   • Format: Text lliure conversacional (castellà)")
print("   • Components: Díodes (tots els tipus) i Transistors")
print("   • Estil: Friendly i informal")
print()
print("3️⃣  TEMPLATE_FARNELL")
print("   • Format: Caòtic/realista (mix català/castellà)")
print("   • Components: Relays, Transformer, Switches, Buzzer, Fuse")
print("   • Estil: Desorganitzat però amb info útil")
print()
print("=" * 80)
print("💡 NOTA IMPORTANT per als assistents:")
print("=" * 80)
print()
print("Aquests templates són EXEMPLES per ajudar-vos a respondre.")
print("Podeu (i hauríeu de):")
print("  • Canviar els preus lleugerament")
print("  • Afegir o treure alguna línia")
print("  • Modificar l'estil segons el vostre proveïdor")
print()
print("L'objectiu és que cada resposta sigui LLEUGERAMENT DIFERENT")
print("per simular la varietat real de respostes de proveïdors.")
print()
print("=" * 80)

📋 TEMPLATES DE RESPOSTA AMB COMPONENTS REALS JCM

✅ 3 templates creats amb components del BOM TESTBOM:

1️⃣  TEMPLATE_DIGIKEY
   • Format: Taula estructurada (professional)
   • Components: ICs, Switches, Buzzer, Fuse
   • Estil: Formal i organitzat

2️⃣  TEMPLATE_MOUSER
   • Format: Text lliure conversacional (castellà)
   • Components: Díodes (tots els tipus) i Transistors
   • Estil: Friendly i informal

3️⃣  TEMPLATE_FARNELL
   • Format: Caòtic/realista (mix català/castellà)
   • Components: Relays, Transformer, Switches, Buzzer, Fuse
   • Estil: Desorganitzat però amb info útil

💡 NOTA IMPORTANT per als assistents:

Aquests templates són EXEMPLES per ajudar-vos a respondre.
Podeu (i hauríeu de):
  • Canviar els preus lleugerament
  • Afegir o treure alguna línia
  • Modificar l'estil segons el vostre proveïdor

L'objectiu és que cada resposta sigui LLEUGERAMENT DIFERENT
per simular la varietat real de respostes de proveïdors.



### 6.3 Agent Email Sender (actualitzat amb Gmail)

Actualitzem l'agent RFQ Generator per usar la nova tool de Gmail:

In [16]:
from crewai import Agent

agent_email_sender = Agent(
    role="Especialista en Enviar RFQs per Email",
    goal="Enviar emails RFQ professionals a companys de treball simulant proveïdors",
    backstory="""
    Ets un especialista en comunicació B2B amb 10 anys d'experiència.
    
    La teva expertesa és:
    - Preparar el contingut d'emails RFQ
    - Enviar emails via Gmail de manera professional
    - Assegurar que tota la informació necessària està present
    - Confirmar l'enviament correcte
    
    Tens accés a eines per enviar emails via Gmail API.
    
    Sempre confirmes que l'email s'ha enviat correctament abans de continuar.
    """,
    tools=[send_email_gmail],
    llm=OPENAI_MODEL,
    verbose=True
)

print("✅ Agent 'Email Sender' creat amb Gmail tool!")

✅ Agent 'Email Sender' creat amb Gmail tool!


### 6.4 Configuració dels emails dels 3 voluntaris

**⚠️ FORMADOR:** Abans d'executar, configura els emails dels 3 voluntaris que participaran:

In [17]:
# ═══════════════════════════════════════════════════════════
# CONFIGURACIÓ DELS 3 VOLUNTARIS
# ═══════════════════════════════════════════════════════════
# Formador: Omple amb els emails dels 3 voluntaris escollits

# El MEU email (formador)
MY_EMAIL = "jberings01@gmail.com"  # ← Email del formador

# Emails dels 3 voluntaris
VOLUNTARI_DIGIKEY = "jberingues@jcm-tech.com"   # ← Email Voluntari 1 (DigiKey)
VOLUNTARI_MOUSER = "jberingues@jcm-tech.com"    # ← Email Voluntari 2 (Mouser)
VOLUNTARI_FARNELL = "jberingues@jcm-tech.com"   # ← Email Voluntari 3 (Farnell)

# ═══════════════════════════════════════════════════════════

print("✅ Configuració dels voluntaris:")
print(f"   Formador: {MY_EMAIL}")
print(f"\n   Voluntari DigiKey:  {VOLUNTARI_DIGIKEY}")
print(f"   Voluntari Mouser:   {VOLUNTARI_MOUSER}")
print(f"   Voluntari Farnell:  {VOLUNTARI_FARNELL}")
print(f"\n💡 Quan s'executin les tasks, s'enviarà un RFQ a cadascun d'ells.")

✅ Configuració dels voluntaris:
   Formador: jberings01@gmail.com

   Voluntari DigiKey:  jberingues@jcm-tech.com
   Voluntari Mouser:   jberingues@jcm-tech.com
   Voluntari Farnell:  jberingues@jcm-tech.com

💡 Quan s'executin les tasks, s'enviarà un RFQ a cadascun d'ells.


### 6.5 Tasks: Enviar RFQs als 3 voluntaris

Crearem 3 tasks separades per enviar cada RFQ al voluntari corresponent:

In [18]:
task_send_all_rfqs = Task(
    description=f"""
    Envia els 3 RFQs generats als seus destinataris corresponents.
    
    Del context (task anterior), tens 3 RFQs:
    1. RFQ DigiKey
    2. RFQ Mouser
    3. RFQ Farnell
    
    Envia CADA UN d'ells al seu destinatari:
    
    1. RFQ DigiKey → {VOLUNTARI_DIGIKEY}
       Assumpte: "RFQ DigiKey - Sol·licitud de cotització #RFQ-2025-001"
    
    2. RFQ Mouser → {VOLUNTARI_MOUSER}
       Assumpte: "RFQ Mouser - Sol·licitud de cotització #RFQ-2025-001"
    
    3. RFQ Farnell → {VOLUNTARI_FARNELL}
       Assumpte: "RFQ Farnell - Sol·licitud de cotització #RFQ-2025-001"
    
    Usa la tool 'Send Email via Gmail' per enviar CADA email.
    
    IMPORTANT: Has d'enviar els 3 emails. NO et quedis només amb un.
    """,
    expected_output=f"""
    Confirmació dels 3 enviaments:
    
    ✅ RFQ DigiKey enviat a {VOLUNTARI_DIGIKEY}
    ✅ RFQ Mouser enviat a {VOLUNTARI_MOUSER}
    ✅ RFQ Farnell enviat a {VOLUNTARI_FARNELL}
    
    Tots els emails han estat enviats correctament.
    """,
    agent=agent_email_sender,
    context=[task_generate_rfqs]
)

### 6.6 Executar: Enviar RFQ

Ara executem el sistema complet fins aquest punt:

In [19]:
crew_send_rfqs = Crew(
    agents=[agent_bom_analyzer, agent_rfq_generator, agent_email_sender],
    tasks=[
        task_analyze_bom,
        task_generate_rfqs,
        task_send_all_rfqs  # ← Una sola task que envia els 3
    ],
    process=Process.sequential,
    verbose=True
)

print("🚀 Executant sistema complet: Analitzar BOM → Generar RFQs → Enviar als 3 Voluntaris\n")
print("=" * 80)
print(f"\n📧 S'enviaran RFQs a:")
print(f"   • DigiKey:  {VOLUNTARI_DIGIKEY}")
print(f"   • Mouser:   {VOLUNTARI_MOUSER}")
print(f"   • Farnell:  {VOLUNTARI_FARNELL}")
print("\n⏳ Això pot trigar 2-3 minuts...\n")
print("=" * 80)

result_send = crew_send_rfqs.kickoff()

print("\n" + "=" * 80)
print("✅ RFQs enviats correctament!")
print("=" * 80)
print("\n📊 RESULTAT:\n")
print(result_send)
print("\n" + "=" * 80)
print(f"\n💡 Els 3 voluntaris haurien de rebre els seus emails ara.")
print(f"   {VOLUNTARI_DIGIKEY} → RFQ DigiKey")
print(f"   {VOLUNTARI_MOUSER} → RFQ Mouser")
print(f"   {VOLUNTARI_FARNELL} → RFQ Farnell")

🚀 Executant sistema complet: Analitzar BOM → Generar RFQs → Enviar als 3 Voluntaris


📧 S'enviaran RFQs a:
   • DigiKey:  jberingues@jcm-tech.com
   • Mouser:   jberingues@jcm-tech.com
   • Farnell:  jberingues@jcm-tech.com

⏳ Això pot trigar 2-3 minuts...



╭──────────────────────────────────────────── Crew Execution Started ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Started                                                                                         │
│  Name: crew                                                                                                     │
│  ID: e168b9ad-37ae-4026-819a-39accd54b27d                                                                       │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert Analitzador de BOMs                                                                              │
│                                                                                                                 │
│  Task:                                                                                                          │
│      Analitza el BOM REAL de JCM del fitxer 'data/Bill_of_Materials-TESTBOM.xlsx'.                              │
│                                                                                                                 │
│      Has de:                                                                                                    │
│      1. Llegir el fitxer Excel amb la tool disponible                                                           │
│      2. DISTRIBUIR els components segons especialització del proveïdor:                                         │
│                                                                                                                 │
│         **DigiKey (especialista en ICs i electrònica digital):**                                                │
│         - Microcontroladors (MCU)                                                                               │
│         - ICs (reguladors de voltatge, etc.)                                                                    │
│         - Tots els altres components que no siguin específics d'altres proveïdors                               │
│                                                                                                                 │
│         **Farnell (especialista en components de potència):**                                                   │
│         - Relés                                                                                                 │
│         - Transformers                                                                                          │
│         - Tots els altres components que no siguin específics d'altres proveïdors                               │
│                                                                                                                 │
│         **Mouser (especialista en semiconductors discrets):**                                                   │
│         - Díodes (tots els tipus: Schottky, Zener, LEDs, rectificadors)                                         │
│         - Transistors                                                                                           │
│         - Tots els altres components que no siguin específics d'altres proveïdors                               │
│                                                                                                                 │
│      3. Prioritzar per:                                                                                         │
│         - Cost estimat (ICs, relés, transformers > LEDs, díodes > resistències)                                 │
│         - Criticitat per al funcionament (MCU, regulador, relay són crítics)                                    │
│         - Quantitat necessària (més quantitat = més prioritat)                                                  │
│      4. Per cada component seleccionat, proporciona:                                                            │
│         - Part Number EXACTE (el codi MATERIAL com apareix al BOM)                                              │
│         - Descripció completa                                                                                   │
│         - Quantitat necessària                                                                                  │
│         - Prioritat (high/medium/low)                  

Output()

Output()

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert Analitzador de BOMs                                                                              │
│                                                                                                                 │
│  Thought: L'objectiu inicial és llegir el fitxer Excel que conté el BOM de JCM per poder començar l'anàlisi     │
│  dels components segons les especificacions proporcionades.                                                     │
│                                                                                                                 │
│  Using Tool: Read BOM Excel                                                                                     │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert Analitzador de BOMs                                                                              │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  ## Component 1                                                                                                 │
│  - **Part Number:** 3005688                                                                                     │
│  - **Descripció:** IC MCU PIC16F18855T-I/SS 8BIT 8KB FLASH                                                      │
│  - **Quantitat:** 1                                                                                             │
│  - **Fabricant:** JCM Technologies                                                                              │
│  - **Prioritat:** high                                                                                          │
│  - **Raó:** És un component crític pel funcionament del sistema.                                                │
│                                                                                                                 │
│  ## Component 2                                                                                                 │
│  - **Part Number:** 3000836                                                                                     │
│  - **Descripció:** IC VOLTAGE REG LDO 5V L7805ABD SMD SO8                                                       │
│  - **Quantitat:** 1                                                                                             │
│  - **Fabricant:** JCM Technologies                                                                              │
│  - **Prioritat:** high                                                                                          │
│  - **Raó:** Regulador de voltatge essencial per al funcionament del circuit.                                    │
│                                                                                                                 │
│  ## Component 3                                                                                                 │
│  - **Part Number:** 3003026                                                                                     │
│  - **Descripció:** RELAY GENERAL PURPOSE DPDT 12V TH                                                            │
│  - **Quantitat:** 2                                                                                             │
│  - **Fabricant:** JCM Technologies                                                                              │
│  - **Prioritat:** high                                                                                          │
│  - **Raó:** Component crític per gestionar el control de potència.                                              │
│                                                                                                                 │
│  ## Component 4                                                                                                 │
│  - **Part Number:** 3003060                                                                                     │
│  - **Descripció:** TRANSFORMER 230VAC 12VAC 2,8VA TH                                                            │
│  - **Quantitat:** 1                                                                                             │
│  - **Fabricant:** JCM Technologies                                                                              │
│  - **Prioritat:** high                                 

Output()

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: 4f616849-8807-4d6b-8c6a-5d5bc6c5774c                                                                     │
│  Agent: Expert Analitzador de BOMs                                                                              │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Generació de RFQs                                                                       │
│                                                                                                                 │
│  Thought: ## RFQ per DigiKey                                                                                    │
│  Thought: Prepare the RFQ for DigiKey with the relevant components.                                             │
│                                                                                                                 │
│  Using Tool: Format RFQ Email                                                                                   │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Generació de RFQs                                                                       │
│                                                                                                                 │
│  Thought: ## RFQ per Mouser                                                                                     │
│  Thought: Prepare the RFQ for Mouser with the relevant components.                                              │
│                                                                                                                 │
│  Using Tool: Format RFQ Email                                                                                   │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Generació de RFQs                                                                       │
│                                                                                                                 │
│  Thought: ## RFQ per Farnell                                                                                    │
│  Thought: Prepare the RFQ for Farnell with the relevant components.                                             │
│                                                                                                                 │
│  Using Tool: Format RFQ Email                                                                                   │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Generació de RFQs                                                                       │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  ## RFQ per DigiKey                                                                                             │
│  EMAIL RFQ - RFQ-2025-001                                                                                       │
│                                                                                                                 │
│  De: compras@jcmtechnologies.com                                                                                │
│  Per a: contact@digikey.com                                                                                     │
│  Assumpte: Sol·licitud de cotització #RFQ-2025-001 - Components electrònics                                     │
│  Data: 03/01/2026                                                                                               │
│                                                                                                                 │
│  ──────────────────────────────────────────────────────────────────────                                         │
│                                                                                                                 │
│  Benvolgut/da equip de DigiKey,                                                                                 │
│                                                                                                                 │
│  Des de JCM Technologies, SAU, volem sol·licitar-vos una cotització per                                         │
│  als següents components electrònics per a un projecte de control de portes                                     │
│  automàtiques.                                                                                                  │
│                                                                                                                 │
│  COMPONENTS SOL·LICITATS:                                                                                       │
│  ──────────────────────────────────────────────────────────────────────                                         │
│                                                                                                                 │
│  Part Number: 3005688, Descripció: IC MCU PIC16F18855T-I/SS 8BIT 8KB FLASH, Quantitat: 1                        │
│  Part Number: 3000836, Descripció: IC VOLTAGE REG LDO 5V L7805ABD SMD SO8, Quantitat: 1                         │
│  Part Number: 3003522, Descripció: BUZZER MAG 2KHZ 1.5VDC 12MM EXTERNALTH, Quantitat: 1                         │
│  Part Number: 3003413, Descripció: TACT SWITCH SPST-NO 6X6 LOW TH, Quantitat: 1                                 │
│                                                                                                                 │
│  ──────────────────────────────────────────────────────────────────────                                         │
│                                                                                                                 │
│  INFORMACIÓ ADDICIONAL:                                                                                         │
│                                                                                                                 │
│  - Referència RFQ: RFQ-2025-001                                                                                 │
│  - Data límit resposta: 10/01/2026                     

Output()

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: 3781dc41-b119-487e-aae9-663e2082bdac                                                                     │
│  Agent: Especialista en Generació de RFQs                                                                       │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Enviar RFQs per Email                                                                   │
│                                                                                                                 │
│  Task:                                                                                                          │
│      Envia els 3 RFQs generats als seus destinataris corresponents.                                             │
│                                                                                                                 │
│      Del context (task anterior), tens 3 RFQs:                                                                  │
│      1. RFQ DigiKey                                                                                             │
│      2. RFQ Mouser                                                                                              │
│      3. RFQ Farnell                                                                                             │
│                                                                                                                 │
│      Envia CADA UN d'ells al seu destinatari:                                                                   │
│                                                                                                                 │
│      1. RFQ DigiKey → jberingues@jcm-tech.com                                                                   │
│         Assumpte: "RFQ DigiKey - Sol·licitud de cotització #RFQ-2025-001"                                       │
│                                                                                                                 │
│      2. RFQ Mouser → jberingues@jcm-tech.com                                                                    │
│         Assumpte: "RFQ Mouser - Sol·licitud de cotització #RFQ-2025-001"                                        │
│                                                                                                                 │
│      3. RFQ Farnell → jberingues@jcm-tech.com                                                                   │
│         Assumpte: "RFQ Farnell - Sol·licitud de cotització #RFQ-2025-001"                                       │
│                                                                                                                 │
│      Usa la tool 'Send Email via Gmail' per enviar CADA email.                                                  │
│                                                                                                                 │
│      IMPORTANT: Has d'enviar els 3 emails. NO et quedis només amb un.                                           │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

Output()

🔄 Renovant token...

✅ Token guardat a token.json

✅ Autenticat com: jberings01@gmail.com

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Enviar RFQs per Email                                                                   │
│                                                                                                                 │
│  Thought: Thought: I will send the emails one by one, starting with the RFQ DigiKey.                            │
│                                                                                                                 │
│  Using Tool: Send Email via Gmail                                                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

✅ Autenticat com: jberings01@gmail.com

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Enviar RFQs per Email                                                                   │
│                                                                                                                 │
│  Thought: Thought: Now I will send the RFQ for Mouser to the same recipient.                                    │
│                                                                                                                 │
│  Using Tool: Send Email via Gmail                                                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

✅ Autenticat com: jberings01@gmail.com

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Enviar RFQs per Email                                                                   │
│                                                                                                                 │
│  Thought: Thought: Now I will send the RFQ for Farnell to the same recipient.                                   │
│                                                                                                                 │
│  Using Tool: Send Email via Gmail                                                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Enviar RFQs per Email                                                                   │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  ✅ RFQ DigiKey enviat a jberingues@jcm-tech.com                                                                │
│  ✅ RFQ Mouser enviat a jberingues@jcm-tech.com                                                                 │
│  ✅ RFQ Farnell enviat a jberingues@jcm-tech.com                                                                │
│                                                                                                                 │
│  Tots els emails han estat enviats correctament.                                                                │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: 9957ded2-c45f-4adb-a2c9-e139de5da2b1                                                                     │
│  Agent: Especialista en Enviar RFQs per Email                                                                   │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


✅ RFQs enviats correctament!

📊 RESULTAT:

✅ RFQ DigiKey enviat a jberingues@jcm-tech.com
✅ RFQ Mouser enviat a jberingues@jcm-tech.com
✅ RFQ Farnell enviat a jberingues@jcm-tech.com

Tots els emails han estat enviats correctament.


💡 Els 3 voluntaris haurien de rebre els seus emails ara.
   jberingues@jcm-tech.com → RFQ DigiKey
   jberingues@jcm-tech.com → RFQ Mouser
   jberingues@jcm-tech.com → RFQ Farnell


╭──────────────────────────────────────────────── Crew Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Completed                                                                                       │
│  Name: crew                                                                                                     │
│  ID: e168b9ad-37ae-4026-819a-39accd54b27d                                                                       │
│  Tool Args:                                                                                                     │
│  Final Output: ✅ RFQ DigiKey enviat a jberingues@jcm-tech.com                                                  │
│  ✅ RFQ Mouser enviat a jberingues@jcm-tech.com                                                                 │
│  ✅ RFQ Farnell enviat a jberingues@jcm-tech.com                                                                │
│                                                                                                                 │
│  Tots els emails han estat enviats correctament.                                                                │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Tracing Status ─────────────────────────────────────────────────╮
│                                                                                                                 │
│  Info: Tracing is disabled.                                                                                     │
│                                                                                                                 │
│  To enable tracing, do any one of these:                                                                        │
│  • Set tracing=True in your Crew/Flow code                                                                      │
│  • Set CREWAI_TRACING_ENABLED=true in your project's .env file                                                  │
│  • Run: crewai traces enable                                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

### 6.7 BREAK: Els 3 voluntaris responen (10-15 minuts)

**🕐 Ara farem un BREAK de 10-15 minuts perquè:**

**Els 3 voluntaris:**
1. ✅ Comprovin si han rebut el seu RFQ
2. ✅ Responguin simulant el seu proveïdor assignat:
   - **Voluntari 1** → Respon com a DigiKey (taula estructurada)
   - **Voluntari 2** → Respon com a Mouser (text lliure)
   - **Voluntari 3** → Respon com a Farnell (format caòtic)
3. ✅ Usin el template corresponent com a guia
4. ✅ Personalitzin lleugerament (preus, stock, etc.)

**La resta d'assistents:**
- 👀 Observen com funciona el procés
- ☕ Aprofiten per un cafè
- 🤔 Pensen com aplicar-ho als seus projectes

**🎯 Objectiu:** Tenir 3 respostes reals per processar amb el sistema!
**📋 Instruccions per respondre:**

1. Obre el teu Gmail
2. Busca l'email amb assumpte "Sol·licitud de cotització #RFQ-2025-001"
3. Respon usant el template del teu grup:
   - **Grup DigiKey:** Format taula estructurada
   - **Grup Mouser:** Text lliure conversacional
   - **Grup Farnell:** Format caòtic realista
4. **Inventa preus realistes** pels components (no cal que siguin reals)
5. Envia la resposta!

**💡 Consells:**
- Posa preus variats (alguns cars, alguns econòmics)
- Varia stocks (alguns "en stock", alguns "3-4 setmanes")
- Fes-ho divertit! Simula el teu proveïdor

In [22]:
MY_SUPPLIER_ROLE = "Farnell" # Pot tenir valor "DigiKey" o "Mouser" o "Farnell"

# Mostra el template corresponent segons el rol
print(f"📋 EL TEU TEMPLATE ({MY_SUPPLIER_ROLE}):\n")
print("=" * 80)

if MY_SUPPLIER_ROLE == "DigiKey":
    print(TEMPLATE_DIGIKEY)
elif MY_SUPPLIER_ROLE == "Mouser":
    print(TEMPLATE_MOUSER)
elif MY_SUPPLIER_ROLE == "Farnell":
    print(TEMPLATE_FARNELL)
else:
    print("⚠️ Rol no reconegut! Tria: DigiKey, Mouser o Farnell")

print("\n" + "=" * 80)
print("\n💡 Copia aquest template, omple'l amb preus i respon l'email!")

📋 EL TEU TEMPLATE (Farnell):


De: info@farnell.com
Assumpte: Re: Presupuesto componentes

Buenos días,

RELAY DPDT 12V ref 3003026: 2,85€/ud tenemos 180ud STOCK OK!!! 
Entrega 24-48h península

TRANSFORMER 230VAC→12VAC 2.8VA (3003060) -> precio 4.50 EUR 
stock: 45 pcs, lead time 1 semana aprox

Switches tactiles:
- 3003413 (6x6 LOW): 0.19€ 
- 3003412 (6x6 RAISED RED): 0.24€
Stock ambos OK (2000+ uds)

Buzzer 3003522: 0,98€ tenemos 250ud entrega inmediata

Fusible 6,3A ref 3003494 -> 0,11 EUR stock SI!!! 8000pcs
Portafusibles 3003506: 0,35€ (3000 uds disponibles)

Todos los precios SIN IVA
Portes: 18€ (pedidos >350€ portes gratis)
Forma pago: transferencia 30 días o tarjeta

Saludos
Dpto. Ventas Farnell
info@farnell.com



💡 Copia aquest template, omple'l amb preus i respon l'email!


---
## 7. Agent 3: Email Parser ⭐

**Aquesta és la part més interessant!** L'agent que parseja emails reals amb formats diversos.

### 7.1 Per què aquesta és la part clau?

**El desafiament:**
- ❌ Els emails NO estan estructurats
- ❌ Cada proveïdor usa un format diferent
- ❌ Pot faltar informació
- ❌ Poden haver errors tipogràfics
- ❌ Pot estar en idiomes diversos

**El poder dels LLMs:**
- ✅ Entenen context i significat
- ✅ Poden extreure info de text no estructurat
- ✅ Gestionen formats diversos
- ✅ Normalitzen dades automàticament
- ✅ Toleren errors i inconsistències

**Això NO es pot fer amb regex o parsers tradicionals!**

### 7.2 Crear l'Agent Email Parser

In [23]:
agent_email_parser = Agent(
    role="Expert en Parsing d'Emails de Cotitzacions",
    goal="Extreure preus, stock i condicions d'emails de proveïdors amb formats diversos",
    backstory="""
    Ets un especialista en processament de llenguatge natural amb 10 anys d'experiència
    processant emails comercials.
    
    La teva expertesa és:
    - Llegir emails de proveïdors en formats MOLT diversos
    - Extreure informació clau: preus, stock, lead times, condicions
    - Normalitzar dades (convertir monedes, unitats, dates)
    - Gestionar informació incompleta o ambigua
    - Detectar warnings o condicions especials
    
    Pots processar:
    - Taules ben formatades
    - Text lliure conversacional
    - Formats caòtics o inconsistents
    - Múltiples idiomes (català, castellà, anglès)
    
    Tens accés a eines per llegir emails de Gmail.
    
    MOLT IMPORTANT:
    - Si no trobes una dada, marca-la com "No especificat" (NO inventes!)
    - Si hi ha ambigüitat, indica-ho a les notes
    - Converteix sempre a EUR si cal
    - Normalitza lead times a format estàndard (ex: "3-5 dies", "2 setmanes")
    
    El teu output ha de ser structured amb Pydantic per poder-lo processar després.
    """,
    tools=[fetch_emails_gmail],
    llm=OPENAI_MODEL,
    verbose=True
)

print("✅ Agent 'Email Parser' creat!")

✅ Agent 'Email Parser' creat!


### 7.3 Task: Parse Email Response

In [25]:
task_parse_emails = Task(
    description=f"""
    Llegeix les 3 respostes als RFQs que hem enviat als voluntaris.
    
    Passos:
    1. Usa la tool 'Fetch Emails from Gmail' per llegir emails recents
       Cerca: "subject:cotització OR subject:RFQ newer_than:1d"
    
    2. Identifica les 3 respostes dels voluntaris:
       - DigiKey: {VOLUNTARI_DIGIKEY}
       - Mouser: {VOLUNTARI_MOUSER}
       - Farnell: {VOLUNTARI_FARNELL}
    
    3. Per CADA email rebut, extreu:
       - Nom del proveïdor (DigiKey/Mouser/Farnell)
       - Per CADA component mencionat:
         * Part Number (exacte)
         * Preu unitari (convertir a EUR si cal)
         * Stock disponible
         * Lead time
         * MOQ si està especificat
         * Notes especials
       - Informació general:
         * Cost d'enviament
         * Condicions de pagament
         * Validesa de la cotització
    
    CRÍTIC:
    - Gestiona formats diversos (taula, text lliure, caòtic)
    - Si una dada no està, marca-la com "No especificat" (NO inventes!)
    - Normalitza preus (sempre en EUR)
    - Processa les 3 respostes, no només una
    """,
    expected_output="""
    Dades extretes de les 3 respostes en format estructurat:
    
    ## Resposta 1: DigiKey
    - Email: {VOLUNTARI_DIGIKEY}
    - Data: [data]
    
    ### Components:
    - Part Number: [codi], Preu: €X.XX, Stock: [info], Lead time: [temps]
    [... més components ...]
    
    ### Condicions:
    - Enviament: €XX
    - Pagament: [terminis]
    - Validesa: [data]
    
    ## Resposta 2: Mouser
    [... mateix format ...]
    
    ## Resposta 3: Farnell
    [... mateix format ...]
    """,
    agent=agent_email_parser,
    tools=[fetch_emails_gmail]
)

print("✅ Task 'Parse Emails' creada per processar les 3 respostes!")

✅ Task 'Parse Emails' creada per processar les 3 respostes!


### 7.4 Executar Email Parser

**⚠️ Assegura't que:**
1. Han arribat els correus dels voluntaris.

In [29]:
# Crew temporal per provar el parser
crew_parse = Crew(
    agents=[agent_email_parser],
    tasks=[task_parse_emails],  # ← Canviat de task_parse_email a task_parse_emails
    process=Process.sequential,
    verbose=False  # ← Desactivar verbose per evitar RecursionError
)

print("🚀 Executant Email Parser...\n")
print("=" * 70)
print(f"\n📬 Buscant respostes de:")
print(f"   • DigiKey:  {VOLUNTARI_DIGIKEY}")
print(f"   • Mouser:   {VOLUNTARI_MOUSER}")
print(f"   • Farnell:  {VOLUNTARI_FARNELL}")
print("\n⏳ Llegint i processant emails...\n")
print("=" * 70)

result_parse = crew_parse.kickoff()

print("\n" + "=" * 70)
print("✅ Parsing completat!")
print("=" * 70)

# Verificar si és Pydantic
if hasattr(result_parse, 'pydantic') and result_parse.pydantic:
    parsed_data = result_parse.pydantic
    
    print("\n📋 DADES ESTRUCTURADES (Pydantic):\n")
    print(f"Proveïdor: {parsed_data.supplier_name}")  # ← Corregit
    print(f"Email: {parsed_data.supplier_email}")
    print(f"Data: {parsed_data.response_date}")
    
    print(f"\nComponents cotitzats: {len(parsed_data.components)}")  # ← Corregit
    for component in parsed_data.components:  # ← Corregit
        print(f"\n  • {component.part_number}")
        if component.description:
            print(f"    Descripció: {component.description}")
        print(f"    Preu: €{component.unit_price:.2f}")
        print(f"    Stock: {component.stock}")
        print(f"    Lead time: {component.lead_time}")
        if component.moq:
            print(f"    MOQ: {component.moq}")
        if component.notes:
            print(f"    Notes: {component.notes}")
    
    print(f"\n📦 Condicions:")
    print(f"  • Enviament: {parsed_data.shipping_cost}")
    print(f"  • Pagament: {parsed_data.payment_terms}")
    print(f"  • Validesa: {parsed_data.quote_validity}")
    if parsed_data.additional_notes:
        print(f"  • Notes: {parsed_data.additional_notes}")
else:
    # Si no és Pydantic, mostrar text pla
    print("\n📊 DADES EXTRETES:\n")
    print(result_parse)

🚀 Executant Email Parser...


📬 Buscant respostes de:
   • DigiKey:  jberingues@jcm-tech.com
   • Mouser:   jberingues@jcm-tech.com
   • Farnell:  jberingues@jcm-tech.com

⏳ Llegint i processant emails...



╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert en Parsing d'Emails de Cotitzacions                                                              │
│                                                                                                                 │
│  Task:                                                                                                          │
│      Llegeix les 3 respostes als RFQs que hem enviat als voluntaris.                                            │
│                                                                                                                 │
│      Passos:                                                                                                    │
│      1. Usa la tool 'Fetch Emails from Gmail' per llegir emails recents                                         │
│         Cerca: "subject:cotització OR subject:RFQ newer_than:1d"                                                │
│                                                                                                                 │
│      2. Identifica les 3 respostes dels voluntaris:                                                             │
│         - DigiKey: jberingues@jcm-tech.com                                                                      │
│         - Mouser: jberingues@jcm-tech.com                                                                       │
│         - Farnell: jberingues@jcm-tech.com                                                                      │
│                                                                                                                 │
│      3. Per CADA email rebut, extreu:                                                                           │
│         - Nom del proveïdor (DigiKey/Mouser/Farnell)                                                            │
│         - Per CADA component mencionat:                                                                         │
│           * Part Number (exacte)                                                                                │
│           * Preu unitari (convertir a EUR si cal)                                                               │
│           * Stock disponible                                                                                    │
│           * Lead time                                                                                           │
│           * MOQ si està especificat                                                                             │
│           * Notes especials                                                                                     │
│         - Informació general:                                                                                   │
│           * Cost d'enviament                                                                                    │
│           * Condicions de pagament                                                                              │
│           * Validesa de la cotització                                                                           │
│                                                                                                                 │
│      CRÍTIC:                                                                                                    │
│      - Gestiona formats diversos (taula, text lliure, caòtic)                                                   │
│      - Si una dada no està, marca-la com "No especificat" (NO inventes!)                                        │
│      - Normalitza preus (sempre en EUR)                                                                         │
│      - Processa les 3 respostes, no només una          

✅ Autenticat com: jberings01@gmail.com


╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert en Parsing d'Emails de Cotitzacions                                                              │
│                                                                                                                 │
│  Thought: Action: Fetch Emails from Gmail                                                                       │
│                                                                                                                 │
│  Using Tool: Fetch Emails from Gmail                                                                            │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭────────────────────────────────────────────────── Tool Input ───────────────────────────────────────────────────╮
│                                                                                                                 │
│  {                                                                                                              │
│    "query": "subject:cotització OR subject:RFQ newer_than:1d",                                                  │
│    "max_results": 10                                                                                            │
│  }                                                                                                              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭────────────────────────────────────────────────── Tool Output ──────────────────────────────────────────────────╮
│                                                                                                                 │
│  📧 S'han trobat 10 email(s):                                                                                   │
│                                                                                                                 │
│  ================================================================================                               │
│                                                                                                                 │
│  EMAIL 1                                                                                                        │
│  --------------------------------------------------------------------------------                               │
│  De: Jordi Beringues <jberingues@jcm-tech.com>                                                                  │
│  Assumpte: Re: RFQ Farnell - Sol·licitud de cotització #RFQ-2025-001                                            │
│  Data: Sat, 3 Jan 2026 23:16:05 +0100                                                                           │
│  ID: 19b85ef024f9e226                                                                                           │
│  --------------------------------------------------------------------------------                               │
│  COS DEL MISSATGE:                                                                                              │
│                                                                                                                 │
│  Buenos días,                                                                                                   │
│                                                                                                                 │
│  RELAY DPDT 12V ref 3003026: 2,85€/ud tenemos 180ud STOCK OK!!!                                                 │
│  Entrega 24-48h península                                                                                       │
│                                                                                                                 │
│  TRANSFORMER 230VAC→12VAC 2.8VA (3003060) -> precio 4.50 EUR                                                    │
│  stock: 45 pcs, lead time 1 semana aprox                                                                        │
│                                                                                                                 │
│  Switches tactiles:                                                                                             │
│  - 3003413 (6x6 LOW): 0.19€                                                                                     │
│  - 3003412 (6x6 RAISED RED): 0.24€                                                                              │
│  Stock ambos OK (2000+ uds)                                                                                     │
│                                                                                                                 │
│  Buzzer 3003522: 0,98€ tenemos 250ud entrega inmediata                                                          │
│                                                                                                                 │
│  Fusible 6,3A ref 3003494 -> 0,11 EUR stock SI!!! 8000pcs                                                       │
│  Portafusibles 3003506: 0,35€ (3000 uds disponibles)                                                            │
│                                                                                                                 │
│  Todos los precios SIN IVA                                                                                      │
│  Portes: 18€ (pedidos >350€ portes gratis)             

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert en Parsing d'Emails de Cotitzacions                                                              │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  ## Resposta 1: Farnell                                                                                         │
│  - Email: jberingues@jcm-tech.com                                                                               │
│  - Data: 03/01/2026                                                                                             │
│                                                                                                                 │
│  ### Components:                                                                                                │
│  - Part Number: 3003026, Preu: €2.85, Stock: 180, Lead time: 24-48 hores                                        │
│  - Part Number: 3003060, Preu: €4.50, Stock: 45, Lead time: 1 setmana                                           │
│  - Part Number: 3003413, Preu: €0.19, Stock: 2000+, Lead time: No especificat                                   │
│  - Part Number: 3003412, Preu: €0.24, Stock: 2000+, Lead time: No especificat                                   │
│  - Part Number: 3003522, Preu: €0.98, Stock: 250, Lead time: immediat                                           │
│  - Part Number: 3003494, Preu: €0.11, Stock: 8000, Lead time: No especificat                                    │
│  - Part Number: 3003506, Preu: €0.35, Stock: 3000, Lead time: No especificat                                    │
│                                                                                                                 │
│  ### Condicions:                                                                                                │
│  - Enviament: €18                                                                                               │
│  - Pagament: transferencia 30 dies o tarjeta                                                                    │
│  - Validesa: 15/02/2026                                                                                         │
│                                                                                                                 │
│  ## Resposta 2: Mouser                                                                                          │
│  - Email: jberingues@jcm-tech.com                                                                               │
│  - Data: 03/01/2026                                                                                             │
│                                                                                                                 │
│  ### Components:                                                                                                │
│  - Part Number: 3003780, Preu: €0.15, Stock: 2000, Lead time: 2-3 dies                                          │
│  - Part Number: 3003681, Preu: €0.08, Stock: No especificat, Lead time: immediat                                │
│  - Part Number: 3003775, Preu: €0.12, Stock: 5000, Lead time: No especificat                                    │
│  - Part Number: 3003762, Preu: €0.10, Stock: 5000, Lead time: No especificat                                    │
│  - Part Number: 3003807, Preu: €0.06, Stock: No especificat, Lead time: No especificat                          │
│  - Part Number: 3003808, Preu: €0.07, Stock: No especificat, Lead time: No especificat                          │
│  - Part Number: 3003737, Preu: €0.35, Stock: No especif


✅ Parsing completat!

📊 DADES EXTRETES:

## Resposta 1: Farnell
- Email: jberingues@jcm-tech.com
- Data: 03/01/2026

### Components:
- Part Number: 3003026, Preu: €2.85, Stock: 180, Lead time: 24-48 hores
- Part Number: 3003060, Preu: €4.50, Stock: 45, Lead time: 1 setmana
- Part Number: 3003413, Preu: €0.19, Stock: 2000+, Lead time: No especificat
- Part Number: 3003412, Preu: €0.24, Stock: 2000+, Lead time: No especificat
- Part Number: 3003522, Preu: €0.98, Stock: 250, Lead time: immediat
- Part Number: 3003494, Preu: €0.11, Stock: 8000, Lead time: No especificat
- Part Number: 3003506, Preu: €0.35, Stock: 3000, Lead time: No especificat

### Condicions:
- Enviament: €18
- Pagament: transferencia 30 dies o tarjeta
- Validesa: 15/02/2026

## Resposta 2: Mouser
- Email: jberingues@jcm-tech.com
- Data: 03/01/2026

### Components:
- Part Number: 3003780, Preu: €0.15, Stock: 2000, Lead time: 2-3 dies
- Part Number: 3003681, Preu: €0.08, Stock: No especificat, Lead time: immediat
- Part 

### 💡 Observa la màgia!

**El que ha passat:**
1. ✅ L'agent ha llegit un email REAL
2. ✅ Ha entès el format (taula/text/caòtic)
3. ✅ Ha extret preus, stocks, lead times
4. ✅ Ha normalitzat les dades
5. ✅ Ha generat un objecte Pydantic estructurat

**Sense LLMs això seria:**
- ❌ Regex complexos per cada format
- ❌ Múltiples parsers específics
- ❌ Gestió manual d'excepcions
- ❌ Manteniment constant quan formats canvien

**Amb LLMs:**
- ✅ Un sol agent
- ✅ Gestiona tots els formats
- ✅ S'adapta automàticament
- ✅ Entén context i significat

---
## 8. Agents 4 i 5: Comparació i Informe

Ara que tenim les dades extretes, fem la comparativa i generem l'informe final.

### 8.1 Agent Price Comparator

In [30]:
agent_price_comparator = Agent(
    role="Expert en Comparació de Preus i Condicions",
    goal="Comparar cotitzacions de múltiples proveïdors i identificar les millors ofertes",
    backstory="""
    Ets un analista de procurement amb 15 anys d'experiència a JCM Technologies.
    
    La teva expertesa és:
    - Comparar preus de múltiples proveïdors
    - Avaluar NO només el preu, sinó també:
      * Disponibilitat de stock
      * Lead times
      * Condicions de pagament
      * Costos d'enviament
      * Fiabilitat del proveïdor
    
    - Identificar la millor oferta per cada component
    - Calcular costos totals (preu + enviament)
    - Detectar alertes:
      * Stock baix
      * Lead times llargs (>2 setmanes)
      * Preus anormalment alts o baixos
      * MOQ problemàtics
    
    - Generar recomanacions pràctiques
    
    El teu anàlisi sempre considera el COST TOTAL, no només el preu unitari.
    
    Per exemple:
    - Component €3.00 + enviament gratis > Component €2.50 + enviament €30
    - Stock immediat > Preu 10% més baix amb 6 setmanes lead time
    """,
    tools=[],  # No necessita tools, treballa amb dades de context
    llm=OPENAI_MODEL,
    verbose=True
)

print("✅ Agent 'Price Comparator' creat!")

✅ Agent 'Price Comparator' creat!


### 8.2 Task: Compare Prices

In [32]:
task_compare_prices = Task(
    description="""
    Analitza les cotitzacions extretes dels emails i genera una comparativa completa.
    
    Basant-te en les dades de la task anterior (context):
    
    1. Per CADA component:
       - Compara preus unitaris
       - Avalua disponibilitat de stock
       - Compara lead times
       - Identifica la millor oferta
       - Calcula cost total: (preu unitari × quantitat) + proporció enviament
    
    2. Detecta alertes:
       - Components amb stock <10 unitats
       - Lead times >3 setmanes
       - Preus >50% més cars que la mitjana
       - MOQ superior a la quantitat necessària
    
    3. Genera recomanacions:
       - Millor proveïdor per cada component
       - Possibles estalvis
       - Riscos a considerar
       - Alternativa si millor oferta no disponible
    
    4. Calcula cost total del projecte amb:
       - Millor opció per cada component
       - Pitjor opció (per comparar estalvi)
    """,
    expected_output="""
    Informe de comparativa amb aquesta estructura:
    
    ## Resum Executiu
    - Cost total amb millors ofertes: €XXX.XX
    - Cost total amb pitjors ofertes: €XXX.XX
    - Estalvi potencial: €XX.XX (XX%)
    - Components analitzats: [número]
    - Alertes detectades: [número]
    
    ## Comparativa per Component
    
    ### [Part Number]
    - Quantitat necessària: X unitats
    - Proveïdors comparats: [llista]
    - Millor oferta: [Proveïdor] - €X.XX/ud (total: €XX.XX)
    - Diferència vs pitjor: €X.XX (XX%)
    - Stock: [info]
    - Lead time: [temps]
    - ⚠️ Alertes: [si n'hi ha]
    - 💡 Recomanació: [text]
    
    [... repetir per cada component ...]
    
    ## Recomanacions Finals
    1. [Recomanació prioritària]
    2. [Recomanació secundària]
    3. [Consideracions addicionals]
    """,
    agent=agent_price_comparator,
    context=[task_parse_emails]  # Rep les dades parsejades
)

print("✅ Task 'Compare Prices' creada!")

✅ Task 'Compare Prices' creada!


### 8.3 Agent Report Generator

In [33]:
agent_report_generator = Agent(
    role="Especialista en Informes Executius",
    goal="Generar informes professionals i clars per la direcció",
    backstory="""
    Ets un expert en comunicació corporativa amb 10 anys d'experiència.
    
    La teva especialitat és:
    - Generar informes executius clars i concisos
    - Presentar dades complexes de manera entenedora
    - Destacar insights clau (no només dades)
    - Usar visualitzacions quan cal
    - Adaptar el to segons l'audiència
    
    Per informes a direcció:
    - ✅ Comença amb el més important (resum executiu)
    - ✅ Usa números i percentatges (ROI, estalvis)
    - ✅ Destaca riscos i oportunitats
    - ✅ Proporciona recomanacions accionables
    - ✅ Format professional
    
    Els teus informes sempre responen:
    - Què hem trobat?
    - Quant ens costa?
    - Què recomanem?
    - Quins riscos hi ha?
    """,
    tools=[],
    llm=OPENAI_MODEL,
    verbose=True
)

print("✅ Agent 'Report Generator' creat!")

✅ Agent 'Report Generator' creat!


### 8.4 Task: Generate Final Report

In [34]:
task_generate_report = Task(
    description="""
    Genera un informe executiu professional amb tota la informació de cotització.
    
    Basant-te en l'anàlisi comparativa anterior (context):
    
    1. Resum Executiu (el més important al principi):
       - Cost total recomanat
       - Estalvi vs alternatives
       - Principal recomanació
       - Riscos crítics
    
    2. Detall de Cotització:
       - Taula comparativa de components
       - Millor proveïdor per cada component
       - Costos desglosats
    
    3. Anàlisi de Riscos:
       - Components amb stock baix
       - Lead times llargs
       - Dependències d'un sol proveïdor
    
    4. Recomanacions:
       - Ordre de compra recomanat
       - Alternatives per components crítics
       - Accions de seguiment
    
    FORMAT: Markdown professional amb taules i seccions clares.
    TO: Executiu però tècnic (per R+D)
    LONGITUD: Complet però concís (2-3 pàgines)
    """,
    expected_output="""
    Un informe complet en format Markdown amb:
    
    # Informe de Cotització - [Projecte]
    *Data: [data]*
    *Generat per: Sistema automatitzat CrewAI*
    
    ## 📊 Resum Executiu
    [Paràgraf amb el més important]
    
    **Mètriques Clau:**
    - Cost total: €XXX.XX
    - Estalvi vs alternativa: €XX.XX (XX%)
    - Components cotitzats: XX
    - Proveïdors analitzats: X
    
    ## 💰 Detall de Cotització
    [Taula comparativa]
    
    ## ⚠️ Anàlisi de Riscos
    [Llista de riscos]
    
    ## 💡 Recomanacions
    [Llista de recomanacions accionables]
    
    ## 📝 Accions de Seguiment
    [Què cal fer ara]
    """,
    agent=agent_report_generator,
    context=[task_compare_prices]
)

print("✅ Task 'Generate Report' creada!")

✅ Task 'Generate Report' creada!


---
## 9. Integració Completa del Sistema

Ara executem TOT el sistema de cap a cap!

### 9.1 Crear el Crew complet amb tots els agents

In [36]:
from crewai import Agent, Task, Crew, Process

# Crew complet amb tots els agents i tasks
crew_complete_system = Crew(
    agents=[
        agent_bom_analyzer,
        agent_rfq_generator,
        agent_email_sender,
        # (Break: Companys responen)
        agent_email_parser,
        agent_price_comparator,
        agent_report_generator
    ],
    tasks=[
        task_analyze_bom,          # 1. Analitzar BOM
        task_generate_rfqs,        # 2. Generar RFQs
        task_send_all_rfqs,             # 3. Enviar per email
        # [BREAK aquí per respostes]
        task_parse_emails,          # 4. Parsear resposta
        task_compare_prices,       # 5. Comparar preus
        task_generate_report       # 6. Generar informe
    ],
    process=Process.sequential,
    verbose=True
)

print("✅ Crew complet creat amb 6 agents i 6 tasks!")
print("\n📊 Workflow:")
print("  1. BOM Analyzer → Identifica components")
print("  2. RFQ Generator → Genera emails")
print("  3. Email Sender → Envia via Gmail")
print("  4. [BREAK] → Companys responen")
print("  5. Email Parser → Extreu dades")
print("  6. Price Comparator → Analitza ofertes")
print("  7. Report Generator → Informe final")

✅ Crew complet creat amb 6 agents i 6 tasks!

📊 Workflow:
  1. BOM Analyzer → Identifica components
  2. RFQ Generator → Genera emails
  3. Email Sender → Envia via Gmail
  4. [BREAK] → Companys responen
  5. Email Parser → Extreu dades
  6. Price Comparator → Analitza ofertes
  7. Report Generator → Informe final


### 9.2 Opció A: Executar tot (incloent l'enviament)

**⚠️ NOTA:** Això enviarà un email REAL. Només executa si vols fer tot el procés complet.

In [ ]:
# DESCOMENTAR per executar el sistema complet:

# print("🚀 EXECUTANT SISTEMA COMPLET DE COTITZACIÓ\n")
# print("=" * 70)
# print("\n⚠️ Aquest procés:")
# print("  1. Analitzarà el BOM")
# print("  2. Generarà RFQs")
# print(f"  3. Enviarà email a {PARTNER_EMAIL}")
# print("  4. Esperarà que responguis")
# print("  5. Parsearà la resposta")
# print("  6. Compararà preus")
# print("  7. Generarà informe final")
# print("\n⏳ Trigarà ~5 minuts (sense comptar el temps de resposta)\n")
# print("=" * 70)

# result_complete = crew_complete_system.kickoff()

# print("\n" + "=" * 70)
# print("✅ SISTEMA COMPLET EXECUTAT!")
# print("=" * 70)
# print("\n📊 INFORME FINAL:\n")
# print(result_complete)

print("💡 Descomenta el codi de dalt per executar el sistema complet.")
print("   O continua amb l'Opció B per executar només des del parsing.")

### 9.3 Opció B: Executar només parsing + comparació + informe

Si ja has enviat l'RFQ manualment i tens respostes, usa això:

In [39]:
from crewai import Agent, Task, Crew, Process

# ═══════════════════════════════════════════════════════════
# CREW: Parsing → Comparació → Informe
# ═══════════════════════════════════════════════════════════

crew_parse_to_report = Crew(
    agents=[agent_email_parser, agent_price_comparator, agent_report_generator],
    tasks=[task_parse_emails, task_compare_prices, task_generate_report],
    process=Process.sequential,
    verbose=True  
)

print("🚀 Executant sistema complet: Parsing → Comparació → Informe\n")
print("=" * 80)
print("\n📬 Buscant respostes dels 3 voluntaris:")
print(f"   • DigiKey:  {VOLUNTARI_DIGIKEY}")
print(f"   • Mouser:   {VOLUNTARI_MOUSER}")
print(f"   • Farnell:  {VOLUNTARI_FARNELL}")
print("\n⏳ Processant les 3 respostes...\n")
print("   1️⃣  Parsejar emails rebuts")
print("   2️⃣  Comparar preus entre proveïdors")
print("   3️⃣  Generar informe executiu")
print("\n" + "=" * 80)

# Executar
result_parse_to_report = crew_parse_to_report.kickoff()

print("\n" + "=" * 80)
print("✅ PROCÉS COMPLETAT!")
print("=" * 80)
print("\n📊 INFORME FINAL:\n")
print(result_parse_to_report)
print("\n" + "=" * 80)

🚀 Executant sistema complet: Parsing → Comparació → Informe


📬 Buscant respostes dels 3 voluntaris:
   • DigiKey:  jberingues@jcm-tech.com
   • Mouser:   jberingues@jcm-tech.com
   • Farnell:  jberingues@jcm-tech.com

⏳ Processant les 3 respostes...

   1️⃣  Parsejar emails rebuts
   2️⃣  Comparar preus entre proveïdors
   3️⃣  Generar informe executiu



╭──────────────────────────────────────────── Crew Execution Started ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Started                                                                                         │
│  Name: crew                                                                                                     │
│  ID: 2926bae2-2ccd-42ee-a90a-278f6789a2da                                                                       │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert en Parsing d'Emails de Cotitzacions                                                              │
│                                                                                                                 │
│  Task:                                                                                                          │
│      Llegeix les 3 respostes als RFQs que hem enviat als voluntaris.                                            │
│                                                                                                                 │
│      Passos:                                                                                                    │
│      1. Usa la tool 'Fetch Emails from Gmail' per llegir emails recents                                         │
│         Cerca: "subject:cotització OR subject:RFQ newer_than:1d"                                                │
│                                                                                                                 │
│      2. Identifica les 3 respostes dels voluntaris:                                                             │
│         - DigiKey: jberingues@jcm-tech.com                                                                      │
│         - Mouser: jberingues@jcm-tech.com                                                                       │
│         - Farnell: jberingues@jcm-tech.com                                                                      │
│                                                                                                                 │
│      3. Per CADA email rebut, extreu:                                                                           │
│         - Nom del proveïdor (DigiKey/Mouser/Farnell)                                                            │
│         - Per CADA component mencionat:                                                                         │
│           * Part Number (exacte)                                                                                │
│           * Preu unitari (convertir a EUR si cal)                                                               │
│           * Stock disponible                                                                                    │
│           * Lead time                                                                                           │
│           * MOQ si està especificat                                                                             │
│           * Notes especials                                                                                     │
│         - Informació general:                                                                                   │
│           * Cost d'enviament                                                                                    │
│           * Condicions de pagament                                                                              │
│           * Validesa de la cotització                                                                           │
│                                                                                                                 │
│      CRÍTIC:                                                                                                    │
│      - Gestiona formats diversos (taula, text lliure, caòtic)                                                   │
│      - Si una dada no està, marca-la com "No especificat" (NO inventes!)                                        │
│      - Normalitza preus (sempre en EUR)                                                                         │
│      - Processa les 3 respostes, no només una          

Output()

Output()

✅ Autenticat com: jberings01@gmail.com

╭──────────────────────────────────────────── 🔧 Agent Tool Execution ────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert en Parsing d'Emails de Cotitzacions                                                              │
│                                                                                                                 │
│  Thought: Action: Fetch Emails from Gmail                                                                       │
│                                                                                                                 │
│  Using Tool: Fetch Emails from Gmail                                                                            │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert en Parsing d'Emails de Cotitzacions                                                              │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  ## Resposta 1: Farnell                                                                                         │
│  - Email: jberingues@jcm-tech.com                                                                               │
│  - Data: 3 Jan 2026                                                                                             │
│                                                                                                                 │
│  ### Components:                                                                                                │
│  - Part Number: 3003026, Preu: €2.85, Stock: 180, Lead time: 24-48h                                             │
│  - Part Number: 3003060, Preu: €4.50, Stock: 45, Lead time: 1 setmana                                           │
│  - Part Number: 3003413, Preu: €0.19, Stock: 2000+, Lead time: No especificat                                   │
│  - Part Number: 3003412, Preu: €0.24, Stock: 2000+, Lead time: No especificat                                   │
│  - Part Number: 3003522, Preu: €0.98, Stock: 250, Lead time: immediat                                           │
│  - Part Number: 3003494, Preu: €0.11, Stock: 8000, Lead time: No especificat                                    │
│  - Part Number: 3003506, Preu: €0.35, Stock: 3000, Lead time: No especificat                                    │
│                                                                                                                 │
│  ### Condicions:                                                                                                │
│  - Enviament: €18                                                                                               │
│  - Pagament: 30 dies transferència o targeta                                                                    │
│  - Validesa: No especificat                                                                                     │
│                                                                                                                 │
│  ## Resposta 2: Mouser                                                                                          │
│  - Email: jberingues@jcm-tech.com                                                                               │
│  - Data: 3 Jan 2026                                                                                             │
│                                                                                                                 │
│  ### Components:                                                                                                │
│  - Part Number: 3003780, Preu: €0.15, Stock: 2000, Lead time: 2-3 dies                                          │
│  - Part Number: 3003681, Preu: €0.08, Stock: No especificat, Lead time: immediat                                │
│  - Part Number: 3003775, Preu: €0.12, Stock: 5000, Lead time: No especificat                                    │
│  - Part Number: 3003762, Preu: €0.10, Stock: 5000, Lead time: No especificat                                    │
│  - Part Number: 3003807, Preu: €0.06, Stock: No especificat, Lead time: No especificat                          │
│  - Part Number: 3003808, Preu: €0.07, Stock: No especificat, Lead time: No especificat                          │
│  - Part Number: 3003737, Preu: €0.35, Stock: No especif

Output()

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: 0cdfb774-9d99-4fb3-9854-679a6a9f1a62                                                                     │
│  Agent: Expert en Parsing d'Emails de Cotitzacions                                                              │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert en Comparació de Preus i Condicions                                                              │
│                                                                                                                 │
│  Task:                                                                                                          │
│      Analitza les cotitzacions extretes dels emails i genera una comparativa completa.                          │
│                                                                                                                 │
│      Basant-te en les dades de la task anterior (context):                                                      │
│                                                                                                                 │
│      1. Per CADA component:                                                                                     │
│         - Compara preus unitaris                                                                                │
│         - Avalua disponibilitat de stock                                                                        │
│         - Compara lead times                                                                                    │
│         - Identifica la millor oferta                                                                           │
│         - Calcula cost total: (preu unitari × quantitat) + proporció enviament                                  │
│                                                                                                                 │
│      2. Detecta alertes:                                                                                        │
│         - Components amb stock <10 unitats                                                                      │
│         - Lead times >3 setmanes                                                                                │
│         - Preus >50% més cars que la mitjana                                                                    │
│         - MOQ superior a la quantitat necessària                                                                │
│                                                                                                                 │
│      3. Genera recomanacions:                                                                                   │
│         - Millor proveïdor per cada component                                                                   │
│         - Possibles estalvis                                                                                    │
│         - Riscos a considerar                                                                                   │
│         - Alternativa si millor oferta no disponible                                                            │
│                                                                                                                 │
│      4. Calcula cost total del projecte amb:                                                                    │
│         - Millor opció per cada component                                                                       │
│         - Pitjor opció (per comparar estalvi)                                                                   │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Output()

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Expert en Comparació de Preus i Condicions                                                              │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  ## Resum Executiu                                                                                              │
│  - Cost total amb millors ofertes: €XX.XX                                                                       │
│  - Cost total amb pitjors ofertes: €XX.XX                                                                       │
│  - Estalvi potencial: €XX.XX (XX%)                                                                              │
│  - Components analitzats: 13                                                                                    │
│  - Alertes detectades: 0                                                                                        │
│                                                                                                                 │
│  ## Comparativa per Component                                                                                   │
│                                                                                                                 │
│  ### 3003026                                                                                                    │
│  - Quantitat necessària: 1 unitats                                                                              │
│  - Proveïdors comparats: Farnell (€2.85), DigiKey (€2.85)                                                       │
│  - Millor oferta: Farnell - €2.85/ud (total: €2.85)                                                             │
│  - Diferència vs pitjor: €0.00 (0%)                                                                             │
│  - Stock: 180                                                                                                   │
│  - Lead time: 24-48h                                                                                            │
│  - ⚠️ Alertes: cap                                                                                               │
│  - 💡 Recomanació: Comprar a Farnell per immediatesa.                                                           │
│                                                                                                                 │
│  ### 3003060                                                                                                    │
│  - Quantitat necessària: 1 unitats                                                                              │
│  - Proveïdors comparats: Farnell (€4.50), DigiKey (No disponible)                                               │
│  - Millor oferta: Farnell - €4.50/ud (total: €4.50)                                                             │
│  - Diferència vs pitjor: €4.50 (infinit%)                                                                       │
│  - Stock: 45                                                                                                    │
│  - Lead time: 1 setmana                                                                                         │
│  - ⚠️ Alertes: cap                                                                                               │
│  - 💡 Recomanació: Compra a Farnell.                                                                            │
│                                                                                                                 │
│  ### 3003413                                           

Output()

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: f120ab33-5e47-43df-9b99-661b15829190                                                                     │
│  Agent: Expert en Comparació de Preus i Condicions                                                              │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Informes Executius                                                                      │
│                                                                                                                 │
│  Task:                                                                                                          │
│      Genera un informe executiu professional amb tota la informació de cotització.                              │
│                                                                                                                 │
│      Basant-te en l'anàlisi comparativa anterior (context):                                                     │
│                                                                                                                 │
│      1. Resum Executiu (el més important al principi):                                                          │
│         - Cost total recomanat                                                                                  │
│         - Estalvi vs alternatives                                                                               │
│         - Principal recomanació                                                                                 │
│         - Riscos crítics                                                                                        │
│                                                                                                                 │
│      2. Detall de Cotització:                                                                                   │
│         - Taula comparativa de components                                                                       │
│         - Millor proveïdor per cada component                                                                   │
│         - Costos desglosats                                                                                     │
│                                                                                                                 │
│      3. Anàlisi de Riscos:                                                                                      │
│         - Components amb stock baix                                                                             │
│         - Lead times llargs                                                                                     │
│         - Dependències d'un sol proveïdor                                                                       │
│                                                                                                                 │
│      4. Recomanacions:                                                                                          │
│         - Ordre de compra recomanat                                                                             │
│         - Alternatives per components crítics                                                                   │
│         - Accions de seguiment                                                                                  │
│                                                                                                                 │
│      FORMAT: Markdown professional amb taules i seccions clares.                                                │
│      TO: Executiu però tècnic (per R+D)                                                                         │
│      LONGITUD: Complet però concís (2-3 pàgines)                                                                │
│                                                                                                                 │
│                                                        

Output()

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Informes Executius                                                                      │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  # Informe de Cotització - [Projecte]                                                                           │
│  *Data: [data]*                                                                                                 │
│  *Generat per: Sistema automatitzat CrewAI*                                                                     │
│                                                                                                                 │
│  ## 📊 Resum Executiu                                                                                           │
│  El cost total recomanat per als components analitzats és de €XX.XX, amb un estalvi potencial de €XX.XX (XX%)   │
│  en comparació amb les alternatives. La principal recomanació és prioritzar la compra dels components a         │
│  Farnell per la seva immediatesa, i és crucial monitoritzar el stock dels components per evitar ruptures. No    │
│  s’han detectat alertes significatives.                                                                         │
│                                                                                                                 │
│  **Mètriques Clau:**                                                                                            │
│  - Cost total: €XX.XX                                                                                           │
│  - Estalvi vs alternativa: €XX.XX (XX%)                                                                         │
│  - Components cotitzats: 13                                                                                     │
│  - Proveïdors analitzats: X                                                                                     │
│                                                                                                                 │
│  ## 💰 Detall de Cotització                                                                                     │
│                                                                                                                 │
│  | Component | Quantitat Necessària | Proveïdors | Millor Oferta | Cost Total | Stock | Lead Time |             │
│  Recomanació |                                                                                                  │
│  |-----------|----------------------|-------------|---------------|-------------|-------|-----------|---------  │
│  -----|                                                                                                         │
│  | 3003026   | 1 unitat             | Farnell (€2.85), DigiKey (€2.85) | Farnell - €2.85/ud | €2.85      | 180  │
│  | 24-48h    | Comprar a Farnell per immediatesa. |                                                             │
│  | 3003060   | 1 unitat             | Farnell (€4.50), DigiKey (No disponible) | Farnell - €4.50/ud | €4.50     │
│  | 45    | 1 setmana | Compra a Farnell. |                                                                      │
│  | 3003413   | 1 unitat             | Farnell (€0.19), DigiKey (€0.18) | DigiKey - €0.18/ud | €0.18      |      │
│  2000+ | 3 dies    | Comprar a DigiKey per estalvi. |                                                           │
│  | 3003412   | 1 unitat             | Farnell (€0.24), DigiKey (€0.22) | DigiKey - €0.22/ud | €0.22      |      │
│  1500+ | 3 dies    | Comprar a DigiKey per estalvi. |    

Output()


✅ PROCÉS COMPLETAT!

📊 INFORME FINAL:

# Informe de Cotització - [Projecte]  
*Data: [data]*  
*Generat per: Sistema automatitzat CrewAI*  

## 📊 Resum Executiu  
El cost total recomanat per als components analitzats és de €XX.XX, amb un estalvi potencial de €XX.XX (XX%) en comparació amb les alternatives. La principal recomanació és prioritzar la compra dels components a Farnell per la seva immediatesa, i és crucial monitoritzar el stock dels components per evitar ruptures. No s’han detectat alertes significatives.

**Mètriques Clau:**  
- Cost total: €XX.XX  
- Estalvi vs alternativa: €XX.XX (XX%)  
- Components cotitzats: 13  
- Proveïdors analitzats: X  

## 💰 Detall de Cotització  

| Component | Quantitat Necessària | Proveïdors | Millor Oferta | Cost Total | Stock | Lead Time | Recomanació |
|-----------|----------------------|-------------|---------------|-------------|-------|-----------|--------------|
| 3003026   | 1 unitat             | Farnell (€2.85), DigiKey (€2.85) | F

╭──────────────────────────────────────────────── Task Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: 54ebdb13-7fb7-43d8-9853-01c6b77b055a                                                                     │
│  Agent: Especialista en Informes Executius                                                                      │
│  Tool Args:                                                                                                     │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Crew Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Completed                                                                                       │
│  Name: crew                                                                                                     │
│  ID: 2926bae2-2ccd-42ee-a90a-278f6789a2da                                                                       │
│  Tool Args:                                                                                                     │
│  Final Output: # Informe de Cotització - [Projecte]                                                             │
│  *Data: [data]*                                                                                                 │
│  *Generat per: Sistema automatitzat CrewAI*                                                                     │
│                                                                                                                 │
│  ## 📊 Resum Executiu                                                                                           │
│  El cost total recomanat per als components analitzats és de €XX.XX, amb un estalvi potencial de €XX.XX (XX%)   │
│  en comparació amb les alternatives. La principal recomanació és prioritzar la compra dels components a         │
│  Farnell per la seva immediatesa, i és crucial monitoritzar el stock dels components per evitar ruptures. No    │
│  s’han detectat alertes significatives.                                                                         │
│                                                                                                                 │
│  **Mètriques Clau:**                                                                                            │
│  - Cost total: €XX.XX                                                                                           │
│  - Estalvi vs alternativa: €XX.XX (XX%)                                                                         │
│  - Components cotitzats: 13                                                                                     │
│  - Proveïdors analitzats: X                                                                                     │
│                                                                                                                 │
│  ## 💰 Detall de Cotització                                                                                     │
│                                                                                                                 │
│  | Component | Quantitat Necessària | Proveïdors | Millor Oferta | Cost Total | Stock | Lead Time |             │
│  Recomanació |                                                                                                  │
│  |-----------|----------------------|-------------|---------------|-------------|-------|-----------|---------  │
│  -----|                                                                                                         │
│  | 3003026   | 1 unitat             | Farnell (€2.85), DigiKey (€2.85) | Farnell - €2.85/ud | €2.85      | 180  │
│  | 24-48h    | Comprar a Farnell per immediatesa. |                                                             │
│  | 3003060   | 1 unitat             | Farnell (€4.50), DigiKey (No disponible) | Farnell - €4.50/ud | €4.50     │
│  | 45    | 1 setmana | Compra a Farnell. |                                                                      │
│  | 3003413   | 1 unitat             | Farnell (€0.19), DigiKey (€0.18) | DigiKey - €0.18/ud | €0.18      |      │
│  2000+ | 3 dies    | Comprar a DigiKey per estalvi. |                                                           │
│  | 3003412   | 1 unitat             | Farnell (€0.24), D

╭──────────────────────────────────────────────── Tracing Status ─────────────────────────────────────────────────╮
│                                                                                                                 │
│  Info: Tracing is disabled.                                                                                     │
│                                                                                                                 │
│  To enable tracing, do any one of these:                                                                        │
│  • Set tracing=True in your Crew/Flow code                                                                      │
│  • Set CREWAI_TRACING_ENABLED=true in your project's .env file                                                  │
│  • Run: crewai traces enable                                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

### 9.4 Guardar l'informe

Guardem l'informe generat a un fitxer Markdown:

In [40]:
# ═══════════════════════════════════════════════════════════
# GUARDAR INFORME
# ═══════════════════════════════════════════════════════════

import os
from datetime import datetime
from IPython.display import Markdown, display

# Crear directori d'outputs si no existeix
os.makedirs('outputs', exist_ok=True)

# Nom del fitxer amb timestamp
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
filename = f"outputs/informe_cotitzacio_{timestamp}.md"

# Guardar informe
with open(filename, 'w', encoding='utf-8') as f:
    f.write(str(result_parse_to_report))

print(f"\n💾 Informe guardat a: {filename}")

# Mostrar informe formatat al notebook
print("\n" + "=" * 80)
print("📄 INFORME FORMATAT")
print("=" * 80)
print()

display(Markdown(str(result_parse_to_report)))

print("\n💡 L'informe també s'ha guardat com a fitxer Markdown.")


💾 Informe guardat a: outputs/informe_cotitzacio_20260104_074940.md

📄 INFORME FORMATAT



# Informe de Cotització - [Projecte]  
*Data: [data]*  
*Generat per: Sistema automatitzat CrewAI*  

## 📊 Resum Executiu  
El cost total recomanat per als components analitzats és de €XX.XX, amb un estalvi potencial de €XX.XX (XX%) en comparació amb les alternatives. La principal recomanació és prioritzar la compra dels components a Farnell per la seva immediatesa, i és crucial monitoritzar el stock dels components per evitar ruptures. No s’han detectat alertes significatives.

**Mètriques Clau:**  
- Cost total: €XX.XX  
- Estalvi vs alternativa: €XX.XX (XX%)  
- Components cotitzats: 13  
- Proveïdors analitzats: X  

## 💰 Detall de Cotització  

| Component | Quantitat Necessària | Proveïdors | Millor Oferta | Cost Total | Stock | Lead Time | Recomanació |
|-----------|----------------------|-------------|---------------|-------------|-------|-----------|--------------|
| 3003026   | 1 unitat             | Farnell (€2.85), DigiKey (€2.85) | Farnell - €2.85/ud | €2.85      | 180   | 24-48h    | Comprar a Farnell per immediatesa. |
| 3003060   | 1 unitat             | Farnell (€4.50), DigiKey (No disponible) | Farnell - €4.50/ud | €4.50      | 45    | 1 setmana | Compra a Farnell. |
| 3003413   | 1 unitat             | Farnell (€0.19), DigiKey (€0.18) | DigiKey - €0.18/ud | €0.18      | 2000+ | 3 dies    | Comprar a DigiKey per estalvi. |
| 3003412   | 1 unitat             | Farnell (€0.24), DigiKey (€0.22) | DigiKey - €0.22/ud | €0.22      | 1500+ | 3 dies    | Comprar a DigiKey per estalvi. |
| 3003522   | 1 unitat             | Farnell (€0.98), DigiKey (€0.95) | DigiKey - €0.95/ud | €0.95      | 300+  | 5 dies    | Comprar a DigiKey per estalvi. |
| 3003494   | 1 unitat             | Farnell (€0.11), DigiKey (€0.12) | Farnell - €0.11/ud | €0.11      | 8000  | No especificat | Comprar a Farnell. |
| 3003780   | 1 unitat             | Mouser (€0.15) | Mouser - €0.15/ud | €0.15      | 2000  | 2-3 dies | Comprar a Mouser. |
| 3003681   | 1 unitat             | Mouser (€0.08) | Mouser - €0.08/ud | €0.08      | No especificat | immediat | Comprar a Mouser. |
| 3003775   | 1 unitat             | Mouser (€0.12) | Mouser - €0.12/ud | €0.12      | 5000  | No especificat | Comprar a Mouser. |
| 3003762   | 1 unitat             | Mouser (€0.10) | Mouser - €0.10/ud | €0.10      | 5000  | No especificat | Comprar a Mouser. |
| 3003807   | 1 unitat             | Mouser (€0.06) | Mouser - €0.06/ud | €0.06      | No especificat | No especificat | Comprar a Mouser. |
| 3003808   | 1 unitat             | Mouser (€0.07) | Mouser - €0.07/ud | €0.07      | No especificat | No especificat | Comprar a Mouser. |
| 3003737   | 1 unitat             | Mouser (€0.35) | Mouser - €0.35/ud | €0.35      | No especificat | No especificat | Comprar a Mouser. |
| 3003669   | 1 unitat             | Mouser (€0.04) | Mouser - €0.04/ud | €0.04      | No especificat | No especificat | Comprar a Mouser. |

## ⚠️ Anàlisi de Riscos  
- Components amb stock baix: 3003060, 3003522.  
- Lead times llargs per a components amb urgència potencial: 3003060.  
- Dependències d'un sol proveïdor: 3003060 (només disponible a Farnell).  

## 💡 Recomanacions  
1. Prioritzar la compra dels components a Farnell per peces amb menor lead time (ex: 3003060).  
2. Considerar estalviar comprant components de DigiKey quan sigui possible (ex: 3003413, 3003412).  
3. Monitoritzar l'estoc dels components amb disponibilitats limitades per evitar ruptures d'estoc.

## 📝 Accions de Seguiment  
- Realitzar la comanda dels components recomanats immediatament per evitar endarreriments.  
- Supervisar l'evolució del stock dels components clau durant les properes setmanes.  
- Revisar alternatives d'abastiment per als components amb dependències crítiques.  

*Nota: Les inversions en stock i adquisicions adequades asseguraran el bon funcionament del projecte i evitaran costos addicionals.*


💡 L'informe també s'ha guardat com a fitxer Markdown.


---
## 🎉 Felicitats!

Has completat el cas pràctic complet i has construït un sistema real i funcional!

**El que has après:**
- ✅ Crear sistemes multi-agent complexos
- ✅ Integrar amb Gmail API (email real)
- ✅ Parsing intel·ligent de text no estructurat
- ✅ Structured outputs amb Pydantic
- ✅ Workflows seqüencials amb dependències
- ✅ Gestió d'errors i fallbacks
- ✅ Generació d'informes professionals

**El que has construït:**
Un sistema que:
1. Analitza BOMs automàticament
2. Genera i envia RFQs per email
3. Parseja respostes en formats diversos
4. Compara preus i condicions
5. Genera informes executius

**I tot això amb només 6 agents i ~300 línies de codi! 🚀**

**Properes passes:**
- Adapta'l al teu cas d'ús específic a JCM
- Integra amb els vostres sistemes (ERP, Outlook, etc.)
- Afegeix més agents per funcionalitats addicionals
- Comparteix amb l'equip i itereu junts

**Gràcies per participar en aquesta formació! 🙏**